insert into core_r_modules (MODULE_CODE, MODULE_ID, PARENT_MODULE_ID, NAME_MLL_CODE, SHORT_NAME_MLL_CODE, IABS_TASK_CODE, PAGE_URL, ORDER_BY, MODULE_MENU_TYPE, STATE)
values ('PF', 3, 0, 'PF_MENU_GROUP', 'PF_MENU_GROUP', null, '#', 3, null, 'A');

insert into core_r_modules (MODULE_CODE, MODULE_ID, PARENT_MODULE_ID, NAME_MLL_CODE, SHORT_NAME_MLL_CODE, IABS_TASK_CODE, PAGE_URL, ORDER_BY, MODULE_MENU_TYPE, STATE)
values ('CL', 4, 0, 'CL', 'CL', null, null, 4, null, 'A');

insert into core_r_modules (MODULE_CODE, MODULE_ID, PARENT_MODULE_ID, NAME_MLL_CODE, SHORT_NAME_MLL_CODE, IABS_TASK_CODE, PAGE_URL, ORDER_BY, MODULE_MENU_TYPE, STATE)
values ('MLT', 1, 0, 'MAIN_MENU_1', 'MAIN_MENU_1', null, null, 1, null, 'A');

insert into core_r_modules (MODULE_CODE, MODULE_ID, PARENT_MODULE_ID, NAME_MLL_CODE, SHORT_NAME_MLL_CODE, IABS_TASK_CODE, PAGE_URL, ORDER_BY, MODULE_MENU_TYPE, STATE)
values ('MPT', 2, 0, 'MANAGE_PRINT_TEMPLATE', 'MANAGE_PRINT_TEMPLATE', null, null, 2, null, 'A');

insert into core_r_modules (MODULE_CODE, MODULE_ID, PARENT_MODULE_ID, NAME_MLL_CODE, SHORT_NAME_MLL_CODE, IABS_TASK_CODE, PAGE_URL, ORDER_BY, MODULE_MENU_TYPE, STATE)
values ('CBR', 5, 0, 'CBR_CB_MENU_GROUP', 'CBR_CB_MENU_GROUP', null, '/ibs/cbr/cbr_catalog.jsp', 5, null, 'A');

