insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CORE', 3003, 1, 'CREATE_USER', 'MENU_USERS', 1, 'A', 'NAV', 3005, 'CREATE_USER', null, -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CORE', 3003, 2, 'EDIT_USER', 'MENU_USERS', 2, 'A', 'NAV', 3005, 'EDIT_USER', 'MODEL_USER', -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CORE', 3003, 3, 'RESET_USER_PASSWORD', 'MENU_USERS', 3, 'A', 'NAV', 3006, 'RESET_USER_PASSWORD', null, -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CORE', 3003, 4, 'ADM_USER_LOCALS', 'MENU_USERS', 4, 'A', 'NAV', 3008, 'ADM_USER_LOCALS', null, -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CORE', 3003, 5, 'ADM_USER_ACCESS', 'MENU_USERS', 5, 'A', 'NAV', 3007, 'ADM_USER_ACCESS', null, -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('04-08-2026 10:24:54', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CBR', 8001, 10, 'CBR_MANUAL_REFRESH', 'CBR_BTN_MANUAL_REFRESH', 10, 'A', 'NAV', null, 'CBR_MANUAL_REFRESH', null, -1, to_date('10-08-2026 12:14:04', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('10-08-2026 12:14:04', 'dd-mm-yyyy hh24:mi:ss'));

insert into CORE_R_MENU_BUTTONS (MODULE_CODE, MENU_ID, BUTTON_ID, ACTION_CODE, NAME_MLL_CODE, ORDER_BY, STATE, BUTTON_TYPE, BUTTON_MENU_ID, PROCESS_CODE, MODEL_PROCESS_CODE, CREATED_BY, CREATED_ON, MODIFY_BY, MODIFY_ON)
values ('CBR', 8001, 11, 'CBR_SET_SCHEDULE', 'CBR_BTN_SET_SCHEDULE', 11, 'A', 'NAV', null, 'CBR_SET_SCHEDULE', null, -1, to_date('10-08-2026 12:14:04', 'dd-mm-yyyy hh24:mi:ss'), -1, to_date('10-08-2026 12:14:04', 'dd-mm-yyyy hh24:mi:ss'));

