insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MLT', 3004, '1000', 'MLT_SUB_STATS', '/ibs/mlt/stats.jsp', 1, 'A', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5005, '5000', 'PF_MENU_DASHBOARD', '/ibs/pf/dashboard.jsp', 0, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('ACC', 7000, '0', 'ACC_MENU_GROUP', '#', 7, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('ACC', 7001, '7000', 'ACC_MENU_ACCOUNT_TYPES', '/ibs/acc/account_types.jsp', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('ESBIN', 3009, '3001', 'MENU_ESBIN', '/ibs/esbin/requests.jsp', 3, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('OSM', 2005, '2006', 'OPERATIONS_DIRECTORY', '/ibs/osm/osms.jsp', 1, 'A', 'MENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('OSM', 2006, '0', 'OSM_DIRECTORY', '#', 1, 'A', 'MENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4002, '4001', 'MPT_MENU_PRODUCTS', '/ibs/mpt/settings.jsp', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4003, '4001', 'MPT_MENU_TEMPLATE_TYPES', '/ibs/mpt/template_types.jsp', 2, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4004, '4001', 'MPT_MENU_MODULES', '/ibs/mpt/modules.jsp', 3, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5000, '0', 'PF_MENU_GROUP', '#', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5001, '5000', 'PF_MENU_PRODUCTS', '/ibs/pf/products.jsp', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5002, '5000', 'PF_MENU_CATEGORIES', '/ibs/pf/categories.jsp', 2, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5003, '5000', 'PF_MENU_ATTRIBUTES', '/ibs/pf/attributes.jsp', 3, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('PF', 5004, '5000', 'PF_MENU_PARAMETERS', '/ibs/pf/parameters.jsp', 4, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CL', 6000, '0', 'CLIENT_MODULE', '#', 1, 'A', 'MENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CL', 6001, '6000', 'CL_SUB_PHYS', '/ibs/cl/phys/phys.jsp', 1, 'A', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CBR', 8000, '0', 'CBR_CB_MENU_GROUP', '#', 8, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CBR', 8001, '8000', 'CBR_CB_MENU_CATALOG', '/ibs/cbr/cbr_catalog.jsp', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3005, '3003', 'MENU_USERS', '/ibs/core/user.jsp', 1, 'A', 'PAGE');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3006, '3003', 'MENU_USERS', '/ibs/core/user_reset_password.jsp', 2, 'A', 'PAGE');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3007, '3003', 'MENU_USERS', '/ibs/core/adm_user_access.jsp', 3, 'A', 'PAGE');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3008, '3003', 'MENU_USERS', '/ibs/core/adm_user_locals.jsp', 4, 'A', 'PAGE');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 9901, '0', 'PUBLIC_PAGE', '/ibs/change_password_first.jsp', 1, 'A', 'PUBLIC');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MLT', 1000, '0', 'MAIN_MENU_1', null, 1, 'A', 'MENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4005, '4001', 'MPT_MENU_PRINT_SETTINGS', '/ibs/mpt/print_settings.jsp', 4, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4006, '4001', 'MPT_MENU_GLOBAL_VARIABLES', '/ibs/mpt/global_variables.jsp', 5, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('ACC', 7002, '7000', 'ACC_MENU_ACCOUNTS', '/ibs/acc/accounts.jsp', 2, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MLT', 2000, '1000', 'MLT_SUB_ERROR', '/ibs/mlt/errors.jsp', 2, 'P', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4000, '0', 'MANAGE_PRINT_TEMPLATE', '#', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MLT', 2001, '1000', 'MLT_SUB_ERROR', '/ibs/mlt/errors.jsp', 5, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MLT', 3000, '1000', 'MLT_SUB_LABEL', '/ibs/mlt/labels.jsp', 3, 'A', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3001, '0', 'MENU_ADMIN_GROUP', '#', 1, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3002, '3001', 'MENU_DASHBOARD', '/ibs/user/util/dashboard/dashboard.jsp', 1, 'A', 'dashboard');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CORE', 3003, '3001', 'MENU_USERS', '/ibs/core/users.jsp', 2, 'A', null);

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('MPT', 4001, '4000', 'MPT_MENU_SETTINGS', '#', 1, 'A', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('CL', 6002, '6000', 'CL_SUB_PHYS_FINANCE', '/ibs/cl/phys/finance/phys_finance.jsp', 2, 'A', 'SUBMENU');

insert into CORE_R_MENUS (MODULE_CODE, MENU_ID, PARENT_MENU_ID, NAME_MLL_CODE, PAGE_URL, ORDER_BY, STATE, MENU_TYPE)
values ('OSM', 2007, '2006', 'OSM_SUBMENU2', '/ibs/osm/osm_methods.jsp', 2, 'A', 'SUBMENU');

