CREATE TABLE PF_APPROVAL_REQUESTS
(
  ID           NUMBER       NOT NULL,
  VERSION_ID   NUMBER       NOT NULL,
  ACTION       VARCHAR2(30) NOT NULL,
  STATE        VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  REQUESTED_BY NUMBER       NOT NULL,
  DECIDED_BY   NUMBER,
  DECIDED_AT   DATE,
  CREATED_BY   NUMBER       NOT NULL,
  CREATED_ON   DATE         DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY  NUMBER       NOT NULL,
  MODIFIED_ON  DATE         DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_APPROVAL_REQUEST_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_APPROVAL_REQUEST_FK1 FOREIGN KEY (VERSION_ID) REFERENCES PF_PRODUCT_VERSIONS (ID),
  CONSTRAINT PF_APPROVAL_REQUEST_C1 CHECK (ACTION IN ('ACTIVATE', 'SUSPEND', 'ARCHIVE')),
  CONSTRAINT PF_APPROVAL_REQUEST_C2 CHECK (STATE IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT PF_APPROVAL_REQUEST_C3 CHECK (DECIDED_BY IS NULL OR DECIDED_BY != REQUESTED_BY)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_APPROVAL_REQUEST_IX1 ON PF_APPROVAL_REQUESTS (VERSION_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_APPROVAL_REQUESTS IS 'Kelishuv so''rovlari (maker-checker)';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.ID IS 'So''rov identifikatori';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.VERSION_ID IS 'Qaysi versiya ustida';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.ACTION IS 'ACTIVATE, SUSPEND, ARCHIVE';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.STATE IS 'PENDING, APPROVED, REJECTED';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.REQUESTED_BY IS 'Maker - so''rovni yuborgan foydalanuvchi';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.DECIDED_BY IS 'Checker - qarorni qabul qilgan foydalanuvchi. REQUESTED_BY dan farqli bo''lishi shart';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.DECIDED_AT IS 'Qaror qabul qilingan vaqt';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.CREATED_BY IS 'Yaratgan foydalanuvchi (User_Env.Get_User_Id) - odatda REQUESTED_BY bilan bir xil';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi (User_Env.Get_User_Id) - odatda DECIDED_BY bilan bir xil';
COMMENT ON COLUMN PF_APPROVAL_REQUESTS.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt';
