CREATE TABLE PF_PRODUCT_VERSIONS
(
  ID                 NUMBER       NOT NULL,
  PRODUCT_ID         NUMBER       NOT NULL,
  VERSION_NO         NUMBER       NOT NULL,
  STATE              VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
  VALID_FROM         DATE,
  VALID_TO           DATE,
  START_DATE         DATE,
  END_DATE           DATE,
  CONTINUE_ON_EXPIRY NUMBER(1)    DEFAULT 0 NOT NULL,
  CREATED_BY         NUMBER       NOT NULL,
  CREATED_ON         DATE         DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY        NUMBER       NOT NULL,
  MODIFIED_ON        DATE         DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_PRODUCT_VERSION_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_VERSION_UK1 UNIQUE (PRODUCT_ID, VERSION_NO) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_VERSION_FK1 FOREIGN KEY (PRODUCT_ID) REFERENCES PF_PRODUCTS (ID),
  CONSTRAINT PF_PRODUCT_VERSION_FK2 FOREIGN KEY (STATE) REFERENCES PF_R_PRODUCT_STATES (CODE),
  CONSTRAINT PF_PRODUCT_VERSION_C2 CHECK (CONTINUE_ON_EXPIRY IN (0, 1))
) TABLESPACE CORE_DATA;

-- Bitta produktda bitta ACTIVE versiya (function-based unique index)
CREATE UNIQUE INDEX PF_PRODUCT_VERSION_UX1
  ON PF_PRODUCT_VERSIONS (CASE WHEN STATE = 'ACTIVE' THEN PRODUCT_ID END) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_PRODUCT_VERSIONS IS 'Produkt versiyalari';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.ID IS 'Versiya identifikatori';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.PRODUCT_ID IS 'Qaysi produktga tegishli';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.VERSION_NO IS 'Tartib raqami';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.STATE IS 'DRAFT -> ON_APPROVAL -> ACTIVE -> SUSPENDED/ARCHIVED';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.VALID_FROM IS 'Shartlar amal qilish oralig''i boshi';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.VALID_TO IS 'Shartlar amal qilish oralig''i oxiri';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.START_DATE IS 'Produktning formadagi amal qilish sanasi boshi';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.END_DATE IS 'Produktning formadagi amal qilish sanasi oxiri';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.CONTINUE_ON_EXPIRY IS '0 - muddat tugaganda bog''liq shartnomalar bloklanadi; 1 - davom etadi';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.CREATED_BY IS 'Maker identifikatori (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_VERSIONS.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt';
