CREATE TABLE PF_PRODUCTS
(
  ID               NUMBER        NOT NULL,
  CATEGORY_ID      NUMBER        NOT NULL,
  CODE             VARCHAR2(50)  NOT NULL,
  NAME             VARCHAR2(255) NOT NULL,
  DELIVERY_TYPE_ID NUMBER        NOT NULL,
  CREATED_BY       NUMBER        NOT NULL,
  CREATED_ON       DATE          DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY      NUMBER        NOT NULL,
  MODIFIED_ON      DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_PRODUCT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_UK1 UNIQUE (CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_FK1 FOREIGN KEY (CATEGORY_ID) REFERENCES PF_R_CATEGORIES (ID),
  CONSTRAINT PF_PRODUCT_FK2 FOREIGN KEY (DELIVERY_TYPE_ID) REFERENCES PF_R_PRODUCT_DELIVERY_TYPES (ID)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_PRODUCT_IX1 ON PF_PRODUCTS (CATEGORY_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_PRODUCTS IS 'Produkt pasporti';
COMMENT ON COLUMN PF_PRODUCTS.ID IS 'Produktning ichki identifikatori';
COMMENT ON COLUMN PF_PRODUCTS.CATEGORY_ID IS 'Qaysi kategoriyaga tegishli. Yaratilgach o''zgartirilmaydi';
COMMENT ON COLUMN PF_PRODUCTS.CODE IS 'Barqaror tashqi kod. ABS shartnomalarda VERSION_NO bilan birga saqlaydi';
COMMENT ON COLUMN PF_PRODUCTS.NAME IS 'Ishchi nomi (ichki foydalanish)';
COMMENT ON COLUMN PF_PRODUCTS.DELIVERY_TYPE_ID IS 'Yetkazish turi (PF_R_PRODUCT_DELIVERY_TYPES)';
COMMENT ON COLUMN PF_PRODUCTS.CREATED_BY IS 'Yaratgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCTS.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_PRODUCTS.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCTS.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt';
