CREATE TABLE PF_PRODUCT_EVENT_OUTBOXES
(
  ID          NUMBER       NOT NULL,
  PRODUCT_ID  NUMBER       NOT NULL,
  EVENT_TYPE  VARCHAR2(50) NOT NULL,
  PAYLOAD     CLOB         NOT NULL,
  SENT_AT     DATE,
  CREATED_BY  NUMBER       NOT NULL,
  CREATED_ON  DATE         DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY NUMBER       NOT NULL,
  MODIFIED_ON DATE         DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_PRODUCT_EVENT_OUTBOX_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_EVENT_OUTBOX_FK1 FOREIGN KEY (PRODUCT_ID) REFERENCES PF_PRODUCTS (ID),
  CONSTRAINT PF_PRODUCT_EVENT_OUTBOX_C1 CHECK (EVENT_TYPE IN ('PRODUCT_ACTIVATED', 'NEW_VERSION_ACTIVATED', 'PRODUCT_SUSPENDED', 'PRODUCT_EXPIRED')),
  CONSTRAINT PF_PRODUCT_EVENT_OUTBOX_C2 CHECK (PAYLOAD IS JSON)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_PRODUCT_EVENT_OUTBOX_IX1 ON PF_PRODUCT_EVENT_OUTBOXES (PRODUCT_ID) TABLESPACE CORE_INDEX;
CREATE INDEX PF_PRODUCT_EVENT_OUTBOX_IX2 ON PF_PRODUCT_EVENT_OUTBOXES (SENT_AT) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_PRODUCT_EVENT_OUTBOXES IS 'Tashqi modullar uchun eventlar (transactional outbox)';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.ID IS 'Event identifikatori, yetkazish tartibi ham shu bo''yicha';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.PRODUCT_ID IS 'Qaysi produktga oid';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.EVENT_TYPE IS 'PRODUCT_ACTIVATED, NEW_VERSION_ACTIVATED, PRODUCT_SUSPENDED, PRODUCT_EXPIRED';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.PAYLOAD IS 'Produkt kodi, versiya, CONTINUE_ON_EXPIRY - JSON ko''rinishida';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.SENT_AT IS 'NULL - navbatda, dispetcher job oladi. To''ldirilgach - yuborilgan';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.CREATED_BY IS 'Yaratgan foydalanuvchi/jarayon (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi/jarayon (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_EVENT_OUTBOXES.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt (masalan SENT_AT to''ldirilganda)';
