CREATE TABLE PF_PRODUCT_PARAMETER_VALUES
(
  ID           NUMBER NOT NULL,
  VERSION_ID   NUMBER NOT NULL,
  PARAMETER_ID NUMBER NOT NULL,
  VALUE        VARCHAR2(4000),
  CREATED_BY   NUMBER NOT NULL,
  CREATED_ON   DATE   DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY  NUMBER NOT NULL,
  MODIFIED_ON  DATE   DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_PRODUCT_PARAMETER_VALUE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_PARAMETER_VALUE_UK1 UNIQUE (VERSION_ID, PARAMETER_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_PARAMETER_VALUE_FK1 FOREIGN KEY (VERSION_ID) REFERENCES PF_PRODUCT_VERSIONS (ID),
  CONSTRAINT PF_PRODUCT_PARAMETER_VALUE_FK2 FOREIGN KEY (PARAMETER_ID) REFERENCES PF_R_PARAMETERS (ID)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_PRODUCT_PARAMETER_VALUE_IX1 ON PF_PRODUCT_PARAMETER_VALUES (PARAMETER_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_PRODUCT_PARAMETER_VALUES IS 'Produkt versiyasi parametr qiymatlari (key-value)';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.ID IS 'Qiymat identifikatori';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.VERSION_ID IS 'Qaysi versiyaga tegishli - eski shartnomalar o''zgarmasligining asosi';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.PARAMETER_ID IS 'Qaysi parametrga (kalitga)';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.VALUE IS 'Qiymat matn ko''rinishida. FUNCTION turdagi parametrlar uchun NULL qoladi';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.CREATED_BY IS 'Yaratgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_PRODUCT_PARAMETER_VALUES.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt';
