--------------------------------------------------------------------------------
-- 3. PF_R_ATTRIBUTE_CATEGORIES (M:N)
--------------------------------------------------------------------------------
CREATE TABLE PF_R_ATTRIBUTE_CATEGORIES
(
  ATTRIBUTE_ID NUMBER NOT NULL,
  CATEGORY_ID  NUMBER NOT NULL,
  CONSTRAINT PF_R_ATTRIBUTE_CATEGORIES_PK PRIMARY KEY (ATTRIBUTE_ID, CATEGORY_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_ATTRIBUTE_CATEGORIES_FK1 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES PF_R_ATTRIBUTES (ID),
  CONSTRAINT PF_R_ATTRIBUTE_CATEGORIES_FK2 FOREIGN KEY (CATEGORY_ID) REFERENCES PF_R_CATEGORIES (ID)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_R_ATTRIBUTE_CATEGORIES_IX1 ON PF_R_ATTRIBUTE_CATEGORIES (CATEGORY_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_R_ATTRIBUTE_CATEGORIES IS 'Atribut <-> kategoriya bog''lanishi (M:N)';
COMMENT ON COLUMN PF_R_ATTRIBUTE_CATEGORIES.ATTRIBUTE_ID IS 'Bog''lanayotgan atribut';
COMMENT ON COLUMN PF_R_ATTRIBUTE_CATEGORIES.CATEGORY_ID IS 'Bog''lanayotgan kategoriya. Kompozit PK - takror bog''lanish taqiqlanadi';


