CREATE TABLE PF_R_PARAMETER_VALIDATIONS
(
  ID            NUMBER        NOT NULL,
  PARAMETER_ID  NUMBER        NOT NULL,
  FUNCTION_ID   NUMBER        NOT NULL,
  CONFIG        CLOB          NOT NULL,
  ML_ERROR_CODE VARCHAR2(100) NOT NULL,
  SORT_ORDER    NUMBER        DEFAULT 0 NOT NULL,
  CONSTRAINT PF_R_PARAMETER_VALIDATIONS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_PARAMETER_VALIDATIONS_UK1 UNIQUE (PARAMETER_ID, FUNCTION_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_PARAMETER_VALIDATIONS_FK1 FOREIGN KEY (PARAMETER_ID) REFERENCES PF_R_PARAMETERS (ID),
  CONSTRAINT PF_R_PARAMETER_VALIDATIONS_FK2 FOREIGN KEY (FUNCTION_ID) REFERENCES PF_R_VALIDATION_FUNCTIONS (ID),
  CONSTRAINT PF_R_PARAMETER_VALIDATIONS_C1 CHECK (CONFIG IS JSON)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_R_PARAMETER_VALIDATIONS_IX1 ON PF_R_PARAMETER_VALIDATIONS (FUNCTION_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_R_PARAMETER_VALIDATIONS IS 'Parametr <-> tekshiruv funksiyasi bog''lanishi';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.ID IS 'Bog''lanish identifikatori';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.PARAMETER_ID IS 'Tekshiriladigan parametr';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.FUNCTION_ID IS 'Qo''llaniladigan funksiya';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.CONFIG IS 'Funksiya argumentlari JSON ko''rinishida, masalan {"min":18,"max":65}';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.ML_ERROR_CODE IS 'Xato matnining ml kodi';
COMMENT ON COLUMN PF_R_PARAMETER_VALIDATIONS.SORT_ORDER IS 'Bir parametrga bir nechta tekshiruv bo''lsa bajarilish tartibi';


