CREATE TABLE PF_R_PRODUCT_STATES
(
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(20)  NOT NULL,
  ML_NAME_CODE VARCHAR2(100) NOT NULL,
  SORT_ORDER   NUMBER        DEFAULT 0 NOT NULL,
  CONSTRAINT PF_R_PRODUCT_STATE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_PRODUCT_STATE_UK1 UNIQUE (CODE) USING INDEX TABLESPACE CORE_INDEX
) TABLESPACE CORE_DATA;

COMMENT ON TABLE PF_R_PRODUCT_STATES IS 'Mahsulot versiyasi holatlari spravochnigi (PF_PRODUCT_VERSIONS.STATE shu yerga FK)';
COMMENT ON COLUMN PF_R_PRODUCT_STATES.ID IS 'Ichki identifikator';
COMMENT ON COLUMN PF_R_PRODUCT_STATES.CODE IS 'Barqaror kod (PF_PRODUCT_VERSIONS.STATE shu qiymatlarga FK qiladi)';
COMMENT ON COLUMN PF_R_PRODUCT_STATES.ML_NAME_CODE IS 'Holat nomining ML kodi';
COMMENT ON COLUMN PF_R_PRODUCT_STATES.SORT_ORDER IS 'Ko''rsatish tartibi';
