CREATE TABLE PF_R_CATEGORIES_H
(
  LOG_ID       NUMBER        NOT NULL,
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(50)  NOT NULL,
  ML_NAME_CODE VARCHAR2(100) NOT NULL,
  STATE        VARCHAR2(1)   NOT NULL,
  ACTION       VARCHAR2(1)   NOT NULL,
  ACTION_DATE  DATE          NOT NULL,
  CONSTRAINT PF_R_CATEGORIES_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_CATEGORIES_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX PF_R_CATEGORIES_H_IX1 ON PF_R_CATEGORIES_H (ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_R_CATEGORIES_H IS 'PF_R_CATEGORIES jadvali uchun o''zgartirishlar tarixi (audit log)';
COMMENT ON COLUMN PF_R_CATEGORIES_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN PF_R_CATEGORIES_H.ID IS 'PF_R_CATEGORIES.ID ga havola (mantiqiy, FK emas - o''chirilgan qatorlar ham saqlanishi kerak)';
COMMENT ON COLUMN PF_R_CATEGORIES_H.ACTION IS 'Amal turi: I-insert, U-update, D-delete';
COMMENT ON COLUMN PF_R_CATEGORIES_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
