CREATE TABLE PF_R_ATTRIBUTES
(
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(50)  NOT NULL,
  ML_NAME_CODE VARCHAR2(100) NOT NULL,
  SOURCE_TYPE  VARCHAR2(20)  NOT NULL,
  MODULE_CODE  VARCHAR2(50),
  SORT_ORDER   NUMBER        DEFAULT 0 NOT NULL,
  CONSTRAINT PF_ATTRIBUTE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_ATTRIBUTE_UK1 UNIQUE (CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_ATTRIBUTE_C1 CHECK (SOURCE_TYPE IN ('EDITABLE', 'MODULE'))
) TABLESPACE CORE_DATA;

COMMENT ON TABLE PF_R_ATTRIBUTES IS 'Atributlar (vkladkalar) - parametrlarni guruhlaydi';
COMMENT ON COLUMN PF_R_ATTRIBUTES.ID IS 'Atributning ichki identifikatori';
COMMENT ON COLUMN PF_R_ATTRIBUTES.CODE IS 'Barqaror texnik kod (GENERAL, SCHEDULE, PERCENT)';
COMMENT ON COLUMN PF_R_ATTRIBUTES.ML_NAME_CODE IS 'Vkladka nomining ml kodi';
COMMENT ON COLUMN PF_R_ATTRIBUTES.SOURCE_TYPE IS 'EDITABLE - parametrlari fabrikada qo''lda yaratiladi; MODULE - tashqi modul shakllantiradi, fabrikada faqat ko''rsatiladi';
COMMENT ON COLUMN PF_R_ATTRIBUTES.MODULE_CODE IS 'SOURCE_TYPE=MODULE bo''lganda mas''ul tashqi tizim (CREDIT_CORE)';
COMMENT ON COLUMN PF_R_ATTRIBUTES.SORT_ORDER IS 'Vkladkalar ko''rsatilish tartibi';


