CREATE TABLE PF_R_PARAMETERS
(
  ID             NUMBER         NOT NULL,
  ATTRIBUTE_ID   NUMBER         NOT NULL,
  CODE           VARCHAR2(100)  NOT NULL,
  ML_NAME_CODE   VARCHAR2(100)  NOT NULL,
  VALUE_TYPE     VARCHAR2(20)   NOT NULL,
  INPUT_TYPE     VARCHAR2(20)   DEFAULT 'MANUAL' NOT NULL,
  CHANGE_POLICY  VARCHAR2(20)   DEFAULT 'VERSIONED' NOT NULL,
  VALUE_FUNCTION VARCHAR2(200),
  REFERENCE_ID   NUMBER,
  IS_REQUIRED    NUMBER(1)      DEFAULT 0 NOT NULL,
  DEFAULT_VALUE  VARCHAR2(4000),
  SORT_ORDER     NUMBER         DEFAULT 0 NOT NULL,
  CONSTRAINT PF_PARAMETER_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PARAMETER_UK1 UNIQUE (ATTRIBUTE_ID, CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PARAMETER_FK1 FOREIGN KEY (ATTRIBUTE_ID) REFERENCES PF_R_ATTRIBUTES (ID),
  CONSTRAINT PF_PARAMETER_FK2 FOREIGN KEY (REFERENCE_ID) REFERENCES PF_R_REFERENCE_VIEWS (ID),
  CONSTRAINT PF_PARAMETER_C1 CHECK (VALUE_TYPE IN ('STRING', 'NUMBER', 'BOOLEAN', 'DATE')),
  CONSTRAINT PF_PARAMETER_C2 CHECK (INPUT_TYPE IN ('MANUAL', 'FUNCTION', 'REFERENCE')),
  CONSTRAINT PF_PARAMETER_C3 CHECK (CHANGE_POLICY IN ('VERSIONED', 'INPLACE')),
  CONSTRAINT PF_PARAMETER_C4 CHECK (IS_REQUIRED IN (0, 1)),
  CONSTRAINT PF_PARAMETER_C5 CHECK (INPUT_TYPE != 'FUNCTION' OR VALUE_FUNCTION IS NOT NULL),
  CONSTRAINT PF_PARAMETER_C6 CHECK (INPUT_TYPE != 'REFERENCE' OR REFERENCE_ID IS NOT NULL)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_PARAMETER_IX1 ON PF_R_PARAMETERS (ATTRIBUTE_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_R_PARAMETERS IS 'Parametrlar (maydonlar)';
COMMENT ON COLUMN PF_R_PARAMETERS.ID IS 'Parametrning ichki identifikatori';
COMMENT ON COLUMN PF_R_PARAMETERS.ATTRIBUTE_ID IS 'Qaysi vkladkaga tegishli';
COMMENT ON COLUMN PF_R_PARAMETERS.CODE IS 'Barqaror kod, bitta ATTRIBUTE_ID ichida unikal (turli atributda bir xil CODE takrorlanishi mumkin). VERSION_RULE shartlarida, ML guruh sifatida va integratsiyalarda ishlatiladi';
COMMENT ON COLUMN PF_R_PARAMETERS.ML_NAME_CODE IS 'Maydon nomining ml kodi';
COMMENT ON COLUMN PF_R_PARAMETERS.VALUE_TYPE IS 'STRING, NUMBER, BOOLEAN, DATE. Barcha qiymatlar skalyar - fabrikada dinamik jadval/setka saqlanmaydi';
COMMENT ON COLUMN PF_R_PARAMETERS.INPUT_TYPE IS 'MANUAL - qo''lda; FUNCTION - qiymat hisoblab beriladi (PF_R_VALUE_FUNCTIONS''da ro''yxatga olingan PLSQL funksiya dinamik chaqiriladi, aks holda PF_VERSION_RULES qoida-jadvali ishlaydi); REFERENCE - qiymat PF_R_REFERENCE_VIEWS orqali ro''yxatdan o''tgan spravochnik view''idan tanlanadi';
COMMENT ON COLUMN PF_R_PARAMETERS.CHANGE_POLICY IS 'VERSIONED - o''zgarishi yangi versiya ochadi; INPLACE - ACTIVE versiyada kelishuvsiz to''g''ridan-to''g''ri o''zgartiriladi';
COMMENT ON COLUMN PF_R_PARAMETERS.VALUE_FUNCTION IS 'INPUT_TYPE=FUNCTION bo''lganda chaqiriladigan PLSQL funksiya nomi (PKG_PERCENT_SVC.F_GET_RATE)';
COMMENT ON COLUMN PF_R_PARAMETERS.REFERENCE_ID IS 'INPUT_TYPE=REFERENCE bo''lganda - PF_R_REFERENCE_VIEWS.ID (qaysi spravochnik view''idan qiymat tanlanadi)';
COMMENT ON COLUMN PF_R_PARAMETERS.IS_REQUIRED IS '1 - kelishuvga yuborishdan oldin qiymat majburiy';
COMMENT ON COLUMN PF_R_PARAMETERS.DEFAULT_VALUE IS 'Yangi versiyada oldindan qo''yiladigan qiymat';
COMMENT ON COLUMN PF_R_PARAMETERS.SORT_ORDER IS 'Maydon tartibi vkladka ichida';


