CREATE TABLE PF_R_PARAMETERS_H
(
  LOG_ID          NUMBER        NOT NULL,
  ID              NUMBER        NOT NULL,
  ATTRIBUTE_ID    NUMBER        NOT NULL,
  CODE            VARCHAR2(100) NOT NULL,
  ML_NAME_CODE    VARCHAR2(100) NOT NULL,
  VALUE_TYPE      VARCHAR2(20)  NOT NULL,
  INPUT_TYPE      VARCHAR2(20)  NOT NULL,
  CHANGE_POLICY   VARCHAR2(20)  NOT NULL,
  VALUE_FUNCTION  VARCHAR2(200),
  REFERENCE_ID    NUMBER,
  IS_REQUIRED     NUMBER(1)     NOT NULL,
  DEFAULT_VALUE   VARCHAR2(4000),
  SORT_ORDER      NUMBER        NOT NULL,
  ACTION          VARCHAR2(1)   NOT NULL,
  ACTION_DATE     DATE          NOT NULL,
  CONSTRAINT PF_R_PARAMETERS_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_PARAMETERS_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX PF_R_PARAMETERS_H_IX1 ON PF_R_PARAMETERS_H (ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_R_PARAMETERS_H IS 'PF_R_PARAMETERS jadvali uchun o''zgartirishlar tarixi (audit log)';
COMMENT ON COLUMN PF_R_PARAMETERS_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN PF_R_PARAMETERS_H.ID IS 'PF_R_PARAMETERS.ID ga havola (mantiqiy, FK emas - o''chirilgan qatorlar ham saqlanishi kerak)';
COMMENT ON COLUMN PF_R_PARAMETERS_H.ACTION IS 'Amal turi: I-insert, U-update, D-delete';
COMMENT ON COLUMN PF_R_PARAMETERS_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
