CREATE TABLE PF_R_VALIDATION_FUNCTIONS
(
  ID         NUMBER        NOT NULL,
  CODE       VARCHAR2(50)  NOT NULL,
  PLSQL_PROC VARCHAR2(200) NOT NULL,
  CONSTRAINT PF_R_VALIDATION_FUNCTIONS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_R_VALIDATION_FUNCTIONS_UK1 UNIQUE (CODE) USING INDEX TABLESPACE CORE_INDEX
) TABLESPACE CORE_DATA;

COMMENT ON TABLE PF_R_VALIDATION_FUNCTIONS IS 'Tekshiruv funksiyalari reyestri';
COMMENT ON COLUMN PF_R_VALIDATION_FUNCTIONS.ID IS 'Funksiya identifikatori';
COMMENT ON COLUMN PF_R_VALIDATION_FUNCTIONS.CODE IS 'Mantiqiy kod (RANGE_CHECK, REGEXP_MATCH)';
COMMENT ON COLUMN PF_R_VALIDATION_FUNCTIONS.PLSQL_PROC IS 'Tekshiruvni bajaruvchi paket.protsedura nomi. Standart imzo: (p_value IN VARCHAR2, p_config IN CLOB), xato bo''lsa RAISE_APPLICATION_ERROR. Dinamik chaqiriladi';


