CREATE TABLE PF_R_PRODUCT_DELIVERY_TYPES
(
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(50)  NOT NULL,
  ML_NAME_CODE VARCHAR2(100) NOT NULL,
  SORT_ORDER   NUMBER        NOT NULL,
  CONSTRAINT PF_PRODUCT_DELIVERY_TYPE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_PRODUCT_DELIVERY_TYPE_UK1 UNIQUE (CODE) USING INDEX TABLESPACE CORE_INDEX
) TABLESPACE CORE_DATA;

COMMENT ON TABLE PF_R_PRODUCT_DELIVERY_TYPES IS 'Produkt yetkazish turlari reyestri (ALL/OFFLINE/ONLINE/EXTERNAL)';
COMMENT ON COLUMN PF_R_PRODUCT_DELIVERY_TYPES.ID IS 'Turning ichki identifikatori';
COMMENT ON COLUMN PF_R_PRODUCT_DELIVERY_TYPES.CODE IS 'Barqaror texnik kod';
COMMENT ON COLUMN PF_R_PRODUCT_DELIVERY_TYPES.ML_NAME_CODE IS 'Nomning ml xizmatidagi kodi';
COMMENT ON COLUMN PF_R_PRODUCT_DELIVERY_TYPES.SORT_ORDER IS 'Ko''rsatilish tartibi';
