CREATE TABLE PF_VERSION_RULES_H
(
  LOG_ID        NUMBER        NOT NULL,
  ID            NUMBER        NOT NULL,
  CATEGORY_ID   NUMBER,
  PRODUCT_ID    NUMBER,
  RULE_TYPE     VARCHAR2(30)  NOT NULL,
  CONDITION     CLOB          NOT NULL,
  TARGET        CLOB          NOT NULL,
  ML_ERROR_CODE VARCHAR2(100) NOT NULL,
  SORT_ORDER    NUMBER,
  CREATED_BY    NUMBER,
  CREATED_ON    DATE,
  MODIFIED_BY   NUMBER,
  MODIFIED_ON   DATE,
  ACTION        VARCHAR2(1)   NOT NULL,
  ACTION_DATE   DATE          NOT NULL,
  PARAMETER_ID  NUMBER,
  CONSTRAINT PF_VERSION_RULES_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_VERSION_RULES_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX PF_VERSION_RULES_H_IX1 ON PF_VERSION_RULES_H (ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_VERSION_RULES_H IS 'PF_VERSION_RULES jadvali uchun o''zgartirishlar tarixi (audit log)';
COMMENT ON COLUMN PF_VERSION_RULES_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN PF_VERSION_RULES_H.ID IS 'PF_VERSION_RULES.ID ga havola (mantiqiy, FK emas - o''chirilgan qatorlar ham saqlanishi kerak)';
COMMENT ON COLUMN PF_VERSION_RULES_H.ACTION IS 'Amal turi: I-insert, U-update, D-delete';
COMMENT ON COLUMN PF_VERSION_RULES_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
