CREATE TABLE PF_VERSION_RULES
(
  ID            NUMBER        NOT NULL,
  CATEGORY_ID   NUMBER,
  PRODUCT_ID    NUMBER,
  PARAMETER_ID  NUMBER        NOT NULL,
  RULE_TYPE     VARCHAR2(30)  NOT NULL,
  CONDITION     CLOB          NOT NULL,
  TARGET        CLOB          NOT NULL,
  ML_ERROR_CODE VARCHAR2(100) NOT NULL,
  SORT_ORDER    NUMBER        DEFAULT 0 NOT NULL,
  CREATED_BY    NUMBER        NOT NULL,
  CREATED_ON    DATE          DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY   NUMBER        NOT NULL,
  MODIFIED_ON   DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PF_VERSION_RULE_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT PF_VERSION_RULE_FK1 FOREIGN KEY (CATEGORY_ID) REFERENCES PF_R_CATEGORIES (ID),
  CONSTRAINT PF_VERSION_RULE_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PF_PRODUCTS (ID),
  CONSTRAINT PF_VERSION_RULE_FK3 FOREIGN KEY (PARAMETER_ID) REFERENCES PF_R_PARAMETERS (ID),
  CONSTRAINT PF_VERSION_RULE_C1 CHECK (RULE_TYPE IN ('REQUIRED_IF', 'FORBIDDEN_IF', 'VALUE_CHECK_IF')),
  CONSTRAINT PF_VERSION_RULE_C2 CHECK (CONDITION IS JSON),
  CONSTRAINT PF_VERSION_RULE_C3 CHECK (TARGET IS JSON),
  CONSTRAINT PF_VERSION_RULE_C4 CHECK (CATEGORY_ID IS NOT NULL OR PRODUCT_ID IS NOT NULL)
) TABLESPACE CORE_DATA;

CREATE INDEX PF_VERSION_RULE_IX1 ON PF_VERSION_RULES (CATEGORY_ID) TABLESPACE CORE_INDEX;
CREATE INDEX PF_VERSION_RULE_IX2 ON PF_VERSION_RULES (PRODUCT_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE PF_VERSION_RULES IS 'Parametrlararo shartli qoidalar (REQUIRED_IF / FORBIDDEN_IF / VALUE_CHECK_IF)';
COMMENT ON COLUMN PF_VERSION_RULES.ID IS 'Qoida identifikatori';
COMMENT ON COLUMN PF_VERSION_RULES.CATEGORY_ID IS 'To''ldirilsa - kategoriyaning barcha produktlariga amal qiladi';
COMMENT ON COLUMN PF_VERSION_RULES.PRODUCT_ID IS 'To''ldirilsa - faqat shu produktga';
COMMENT ON COLUMN PF_VERSION_RULES.PARAMETER_ID IS 'Qoida qaysi parametrga tegishli (TARGET shu parametrga ishora qiladi)';
COMMENT ON COLUMN PF_VERSION_RULES.RULE_TYPE IS 'REQUIRED_IF - PARAMETER_ID majburiy; FORBIDDEN_IF - TARGET mos kelsa taqiqlangan; VALUE_CHECK_IF - PARAMETER_ID qiymati TARGET shartiga javob berishi shart (yoki FUNCTION parametr uchun TARGET.value hisoblangan qiymat sifatida qaytariladi)';
COMMENT ON COLUMN PF_VERSION_RULES.CONDITION IS 'Ishga tushish sharti - JSON massiv: [{"parameter_id":..,"op":"=","value":"...","value2":"..."}]. Operatorlar: =, !=, >, <, >=, <=, BETWEEN, IN (AND bilan birlashadi)';
COMMENT ON COLUMN PF_VERSION_RULES.TARGET IS 'JSON obyekt {"op":"...","value":"...","value2":"..."} - RULE_TYPE ga qarab talqin qilinadi (REQUIRED_IF uchun ishlatilmaydi)';
COMMENT ON COLUMN PF_VERSION_RULES.ML_ERROR_CODE IS 'Qoida buzilganda ko''rsatiladigan xato matni';
COMMENT ON COLUMN PF_VERSION_RULES.SORT_ORDER IS 'Qoidalar bajarilish tartibi';
COMMENT ON COLUMN PF_VERSION_RULES.CREATED_BY IS 'Yaratgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_VERSION_RULES.CREATED_ON IS 'Yaratilgan vaqt';
COMMENT ON COLUMN PF_VERSION_RULES.MODIFIED_BY IS 'Oxirgi o''zgartirgan foydalanuvchi (User_Env.Get_User_Id)';
COMMENT ON COLUMN PF_VERSION_RULES.MODIFIED_ON IS 'Oxirgi o''zgartirilgan vaqt';
