-- =====================================================================
-- ACC_ACCOUNTS - o'z tizimimizda saqlanadigan schet (hisob) jadvali
-- Maqsad: BANK ABS iga pravodka chiqarish va identifikatsiya uchun
--         zarur bo'lgan asosiy ma'lumotlarni saqlash. To'liq schet
--         ma'lumotlari (oborotlar, saldo va h.k.) BANK ABS ida
--         (ACCOUNTS/SALDO jadvallarida) saqlanadi, bu yerda takrorlanmaydi.
--
-- MUHIM: har bir schet SM_OBJECTS da o'zining alohida obyekt yozuviga ega
--        bo'ladi (OBJECT_CODE='ACC_ACCOUNT', RELATION_ID=ACCOUNT_ID orqali,
--        alohida ustun sifatida saqlanmaydi - kerak bo'lganda shu ikki
--        ustun bo'yicha SM_OBJECTS'dan qidiriladi). Shu tufayli schet
--        boshqa har qanday obyekt kabi umumiy obyektlar grafida ishtirok
--        eta oladi.
--
-- NOMLASH KONVENTSIYASI: barcha jadval nomlari "S" bilan tugaydi (ko'plik).
-- Tarix (history) jadvallari tegishli asosiy jadval nomi + "_H" bilan
-- nomlanadi (masalan ACC_ACCOUNT_OBJECTS -> ACC_ACCOUNT_OBJECTS_H).
-- =====================================================================

-- Create table
create table ACC_ACCOUNTS
(
  account_id       NUMBER(19) generated by default as identity,
  account_code     VARCHAR2(20) not null,
  account_type_id  NUMBER(19) not null,
  owner_type       VARCHAR2(1) not null,
  client_id        NUMBER(19),
  code_filial      VARCHAR2(5) not null,
  code_currency    VARCHAR2(3) not null,
  abs_account_id   NUMBER(12),
  account_status   VARCHAR2(1) default 'O' not null,
  date_open        DATE default SYSDATE not null,
  date_close       DATE,
  created_on       DATE default SYSDATE not null,
  created_by       VARCHAR2(50) default USER not null,
  modified_on      DATE,
  modified_by      VARCHAR2(50)
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNTS
  is 'Tizimimizda saqlanadigan schetlar (hisob raqamlar) ro''yxati. BANK ABS dagi
   ACCOUNTS jadvalining qisqartirilgan proyeksiyasi - faqat pravodka chiqarish va
   identifikatsiya uchun zarur bo''lgan asosiy ma''lumotlar saqlanadi. Schet 2 xil
   bo''lishi mumkin: klient nomiga (OWNER_TYPE=C, modul orqali ochiladi) va bank
   nomiga (OWNER_TYPE=B, ABS da ochiladi, bir nechta modulda bir vaqtda ishlatiladi
   - ACC_ACCOUNT_MODULES jadvalida saqlanadi, ostatkasi ABS orqali ham to''g''ridan-
   to''g''ri o''zgarishi mumkin - ACC_ACCOUNT_BALANCES/ACC_ACCOUNT_BALANCES_H
   jadvallarida kuzatiladi). Schet SM_OBJECTS''da (OBJECT_CODE=''ACC_ACCOUNT'',
   RELATION_ID=ACCOUNT_ID) alohida obyekt sifatida ham ro''yxatga olinadi va
   boshqa obyektlarga ACC_ACCOUNT_OBJECTS jadvali orqali bog''lanadi.';

-- Add comments to the columns
comment on column ACC_ACCOUNTS.account_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNTS.account_code
  is '20 xonali schet raqami (BANK ABS dagi to''liq schet kodi)';
comment on column ACC_ACCOUNTS.account_type_id
  is 'Tip schet, FK -> ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID';
comment on column ACC_ACCOUNTS.owner_type
  is 'Schet kimning nomiga ochilganligi: C - klient nomiga, B - bank nomiga';
comment on column ACC_ACCOUNTS.client_id
  is 'Klient, FK -> CL_PHYS_PERSONS.ID (faqat OWNER_TYPE=C bo''lganda to''ldiriladi)';
comment on column ACC_ACCOUNTS.code_filial
  is 'Filial kodi (BANK ABS dagi CODE_FILIAL)';
comment on column ACC_ACCOUNTS.code_currency
  is 'Valyuta kodi';
comment on column ACC_ACCOUNTS.abs_account_id
  is 'BANK ABS dagi ACCOUNTS.ID qiymati - saldo/qoldiqni real vaqtda olish uchun bog''lovchi kalit';
comment on column ACC_ACCOUNTS.account_status
  is 'Schet holati: O - ochiq, C - yopiq, B - bloklangan';
comment on column ACC_ACCOUNTS.date_open
  is 'Schet ochilgan sana';
comment on column ACC_ACCOUNTS.date_close
  is 'Schet yopilgan sana';
comment on column ACC_ACCOUNTS.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNTS.created_by
  is 'Yozuvni yaratgan foydalanuvchi (operator) login';
comment on column ACC_ACCOUNTS.modified_on
  is 'Yozuv oxirgi marta o''zgartirilgan sana/vaqt';
comment on column ACC_ACCOUNTS.modified_by
  is 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi (operator) login';

-- Create/Recreate indexes
create index ACC_ACCOUNTS_I1 on ACC_ACCOUNTS (ACCOUNT_TYPE_ID)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACC_ACCOUNTS_I2 on ACC_ACCOUNTS (CLIENT_ID)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACC_ACCOUNTS_I3 on ACC_ACCOUNTS (CODE_FILIAL)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACC_ACCOUNTS_I4 on ACC_ACCOUNTS (ABS_ACCOUNT_ID)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_PK primary key (ACCOUNT_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_U1 unique (ACCOUNT_CODE)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_F1 foreign key (ACCOUNT_TYPE_ID)
  references ACC_ACCOUNT_TYPES (ACCOUNT_TYPE_ID);
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_F2 foreign key (CLIENT_ID)
  references CL_PHYS_PERSONS (CLIENT_ID);

-- Create/Recreate check constraints
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_C1
  check (OWNER_TYPE in ('C','B'));
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_C2
  check (ACCOUNT_STATUS in ('O','C','B'));
alter table ACC_ACCOUNTS
  add constraint ACC_ACCOUNTS_C3
  check (
    (OWNER_TYPE = 'C' and CLIENT_ID is not null)
    or
    (OWNER_TYPE = 'B' and CLIENT_ID is null)
  );


-- =====================================================================
-- ACC_ACCOUNT_MODULES - bank nomiga ochilgan schetning bir vaqtning
-- o'zida bir nechta modulda foydalanilishini yurituvchi bog'lovchi jadval
-- =====================================================================

-- Create table
create table ACC_ACCOUNT_MODULES
(
  account_module_id NUMBER(19) generated by default as identity,
  account_id         NUMBER(19) not null,
  module_code        VARCHAR2(10) not null,
  is_active_flag     CHAR(1) default 'Y' not null,
  connected_on       DATE default SYSDATE not null,
  disconnected_on    DATE,
  created_on         DATE default SYSDATE not null,
  created_by         VARCHAR2(50) default USER not null
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNT_MODULES
  is 'Bank nomiga ochilgan (OWNER_TYPE=B) schetlarning qaysi modullarda
   foydalanilayotganini yurituvchi bog''lovchi jadval - bitta bank schetidan
   bir vaqtning o''zida bir nechta modul foydalanishi mumkin (many-to-many).';

-- Add comments to the columns
comment on column ACC_ACCOUNT_MODULES.account_module_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_MODULES.account_id
  is 'Schet, FK -> ACC_ACCOUNTS.ACCOUNT_ID';
comment on column ACC_ACCOUNT_MODULES.module_code
  is 'Modul, FK -> ACC_R_MODULES.MODULE_CODE';
comment on column ACC_ACCOUNT_MODULES.is_active_flag
  is 'Modulda hozir foydalanilayotganligi belgisi: Y - foydalanilmoqda, N - to''xtatilgan';
comment on column ACC_ACCOUNT_MODULES.connected_on
  is 'Modul ushbu schetdan foydalana boshlagan sana';
comment on column ACC_ACCOUNT_MODULES.disconnected_on
  is 'Modul ushbu schetdan foydalanishni to''xtatgan sana';
comment on column ACC_ACCOUNT_MODULES.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_MODULES.created_by
  is 'Yozuvni yaratgan foydalanuvchi (operator) login';

-- Create/Recreate indexes
create index ACC_ACCOUNT_MODULES_I1 on ACC_ACCOUNT_MODULES (MODULE_CODE)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNT_MODULES
  add constraint ACC_ACCOUNT_MODULES_PK primary key (ACCOUNT_MODULE_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_MODULES
  add constraint ACC_ACCOUNT_MODULES_U1 unique (ACCOUNT_ID, MODULE_CODE)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_MODULES
  add constraint ACC_ACCOUNT_MODULES_F1 foreign key (ACCOUNT_ID)
  references ACC_ACCOUNTS (ACCOUNT_ID);
alter table ACC_ACCOUNT_MODULES
  add constraint ACC_ACCOUNT_MODULES_F2 foreign key (MODULE_CODE)
  references ACC_R_MODULES (MODULE_CODE);

-- Create/Recreate check constraints
alter table ACC_ACCOUNT_MODULES
  add constraint ACC_ACCOUNT_MODULES_C1
  check (IS_ACTIVE_FLAG in ('Y','N'));


-- =====================================================================
-- ACC_ACCOUNT_OBJECTS - schetning obyekt(lar)ga bog'lanishi va har bir
-- obyekt bo'yicha JORIY ostatka/oborotlarni yuritish uchun "master" jadval
-- (BANK ABS dagi ACCOUNTS jadvaliga o'xshash rol - joriy qiymatlar).
-- Kunlik tarix ACC_ACCOUNT_OBJECTS_H jadvalida saqlanadi (SALDO ga
-- o'xshash rol).
--
-- 1-xolat (schet faqat bitta obyektga bog'langan): shu obyekt uchun bitta
--   qator bo'ladi, va ABS dagi to'liq ostatka shu bitta qatorga teng bo'ladi.
-- 2-xolat (schet bir nechta obyektga bog'langan): har bir obyekt uchun
--   alohida qator bo'ladi, va ularning SALDO_OUT larining yig'indisi
--   ABS dagi schetning umumiy ostatkasiga teng bo'lishi kerak.
-- =====================================================================

-- Create table
create table ACC_ACCOUNT_OBJECTS
(
  account_object_id NUMBER(19) generated by default as identity,
  account_id         NUMBER(19) not null,
  object_id          NUMBER(10) not null,
  saldo_in           NUMBER(20) default 0 not null,
  saldo_out          NUMBER(20) default 0 not null,
  income             NUMBER(20) default 0 not null,
  expense            NUMBER(20) default 0 not null,
  income_all         NUMBER(20) default 0 not null,
  expense_all        NUMBER(20) default 0 not null,
  state              VARCHAR2(1) default 'A' not null,
  date_linked        DATE default SYSDATE not null,
  date_unlinked      DATE,
  created_on         DATE default SYSDATE not null,
  created_by         VARCHAR2(50) default USER not null,
  modified_on        DATE,
  modified_by        VARCHAR2(50)
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNT_OBJECTS
  is 'Schetning qaysi obyekt(lar)ga (SM_OBJECTS) bog''langanligini va har bir
   obyekt bo''yicha JORIY ostatka/oborotlarni (bizning tizimda yurituvchi ulush)
   saqlaydi. Bitta schet bitta yoki bir nechta obyektga bog''lanishi mumkin -
   bir nechta bo''lganda, SALDO_OUT larning yig''indisi ABS dagi schetning
   umumiy ostatkasiga teng bo''lishi kerak. Har oper-kun yopilganda joriy
   qiymatlar ACC_ACCOUNT_OBJECTS_H ga tarix sifatida yoziladi.';

-- Add comments to the columns
comment on column ACC_ACCOUNT_OBJECTS.account_object_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_OBJECTS.account_id
  is 'Schet, FK -> ACC_ACCOUNTS.ACCOUNT_ID';
comment on column ACC_ACCOUNT_OBJECTS.object_id
  is 'Bog''langan obyekt, FK -> SM_OBJECTS.OBJECT_ID';
comment on column ACC_ACCOUNT_OBJECTS.saldo_in
  is 'Ushbu obyekt ulushidagi joriy oper-kun kiruvchi qoldig''i';
comment on column ACC_ACCOUNT_OBJECTS.saldo_out
  is 'Ushbu obyekt ulushidagi joriy (hozirgi) qoldiq';
comment on column ACC_ACCOUNT_OBJECTS.income
  is 'Ushbu obyekt ulushidagi joriy kundagi kirim (BANK ABS dagi TURNOVER_CREDIT/DEBIT ga mos)';
comment on column ACC_ACCOUNT_OBJECTS.expense
  is 'Ushbu obyekt ulushidagi joriy kundagi chiqim';
comment on column ACC_ACCOUNT_OBJECTS.income_all
  is 'Ushbu obyekt ulushi bo''yicha boshidan buyon jami kirim (BANK ABS dagi TURNOVER_ALL_CREDIT/DEBIT ga mos)';
comment on column ACC_ACCOUNT_OBJECTS.expense_all
  is 'Ushbu obyekt ulushi bo''yicha boshidan buyon jami chiqim';
comment on column ACC_ACCOUNT_OBJECTS.state
  is 'Bog''lanish holati: A - faol, C - yopilgan (uzilgan)';
comment on column ACC_ACCOUNT_OBJECTS.date_linked
  is 'Schet ushbu obyektga bog''langan sana';
comment on column ACC_ACCOUNT_OBJECTS.date_unlinked
  is 'Schetning ushbu obyekt bilan bog''lanishi uzilgan sana';
comment on column ACC_ACCOUNT_OBJECTS.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_OBJECTS.created_by
  is 'Yozuvni yaratgan foydalanuvchi (operator) login';
comment on column ACC_ACCOUNT_OBJECTS.modified_on
  is 'Yozuv oxirgi marta o''zgartirilgan sana/vaqt (masalan ostatka yangilanganda)';
comment on column ACC_ACCOUNT_OBJECTS.modified_by
  is 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi (operator/servis) login';

-- Create/Recreate indexes
create index ACC_ACCOUNT_OBJECTS_I1 on ACC_ACCOUNT_OBJECTS (OBJECT_ID)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_PK primary key (ACCOUNT_OBJECT_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_U1 unique (ACCOUNT_ID, OBJECT_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_F1 foreign key (ACCOUNT_ID)
  references ACC_ACCOUNTS (ACCOUNT_ID);
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_F2 foreign key (OBJECT_ID)
  references SM_OBJECTS (OBJECT_ID);

-- Create/Recreate check constraints
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_C1
  check (STATE in ('A','C'));
alter table ACC_ACCOUNT_OBJECTS
  add constraint ACC_ACCOUNT_OBJECTS_C2
  check (INCOME >= 0 and EXPENSE >= 0);


-- =====================================================================
-- ACC_ACCOUNT_OBJECTS_H - ACC_ACCOUNT_OBJECTS uchun oper-kunlar bo'yicha
-- tarix (BANK ABS dagi ACCOUNTS/SALDO munosabatiga o'xshash: ACC_ACCOUNT_OBJECTS
-- = joriy holat, bu jadval = har kunlik yozuv).
-- =====================================================================

-- Create table
create table ACC_ACCOUNT_OBJECTS_H
(
  account_object_hist_id NUMBER(19) generated by default as identity,
  account_object_id       NUMBER(19) not null,
  oper_day                DATE not null,
  saldo_in                NUMBER(20) default 0 not null,
  saldo_out               NUMBER(20) default 0 not null,
  income                  NUMBER(20) default 0 not null,
  expense                 NUMBER(20) default 0 not null,
  income_all              NUMBER(20) default 0 not null,
  expense_all             NUMBER(20) default 0 not null,
  created_on              DATE default SYSDATE not null,
  created_by              VARCHAR2(50) default USER not null
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNT_OBJECTS_H
  is 'ACC_ACCOUNT_OBJECTS dagi har bir schet-obyekt bog''lanishi uchun o''tgan
   oper-kunlar bo''yicha tarixiy ostatka/oborot yozuvlari (BANK ABS dagi SALDO
   jadvaliga mos rol).';

-- Add comments to the columns
comment on column ACC_ACCOUNT_OBJECTS_H.account_object_hist_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_OBJECTS_H.account_object_id
  is 'Schet-obyekt bog''lanishi, FK -> ACC_ACCOUNT_OBJECTS.ACCOUNT_OBJECT_ID';
comment on column ACC_ACCOUNT_OBJECTS_H.oper_day
  is 'Operatsion kun (tarixiy yozuv tegishli bo''lgan oper-kun)';
comment on column ACC_ACCOUNT_OBJECTS_H.saldo_in
  is 'Ushbu oper-kundagi kiruvchi qoldiq';
comment on column ACC_ACCOUNT_OBJECTS_H.saldo_out
  is 'Ushbu oper-kundagi chiquvchi qoldiq';
comment on column ACC_ACCOUNT_OBJECTS_H.income
  is 'Ushbu oper-kundagi kirim';
comment on column ACC_ACCOUNT_OBJECTS_H.expense
  is 'Ushbu oper-kundagi chiqim';
comment on column ACC_ACCOUNT_OBJECTS_H.income_all
  is 'Ushbu oper-kunga qadar boshidan buyon jami kirim';
comment on column ACC_ACCOUNT_OBJECTS_H.expense_all
  is 'Ushbu oper-kunga qadar boshidan buyon jami chiqim';
comment on column ACC_ACCOUNT_OBJECTS_H.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_OBJECTS_H.created_by
  is 'Yozuvni yaratgan foydalanuvchi/servis';

-- Create/Recreate indexes
create index ACC_ACCOUNT_OBJECTS_H_I1 on ACC_ACCOUNT_OBJECTS_H (OPER_DAY)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNT_OBJECTS_H
  add constraint ACC_ACCOUNT_OBJECTS_H_PK primary key (ACCOUNT_OBJECT_HIST_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_OBJECTS_H
  add constraint ACC_ACCOUNT_OBJECTS_H_U1 unique (ACCOUNT_OBJECT_ID, OPER_DAY)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_OBJECTS_H
  add constraint ACC_ACCOUNT_OBJECTS_H_F1 foreign key (ACCOUNT_OBJECT_ID)
  references ACC_ACCOUNT_OBJECTS (ACCOUNT_OBJECT_ID);


-- =====================================================================
-- ACC_ACCOUNT_BALANCES - schetning O'ZIGA TEGISHLI (obyektlarga bo'lmagan)
-- JORIY ostatka/oborot holati - "master" jadval (bitta schet = bitta qator).
-- Ayniqsa BANK NOMIGA ochilgan (OWNER_TYPE=B) schetlar uchun muhim - chunki
-- ularning ostatkasi BANK ABS orqali to'g'ridan-to'g'ri (bizning modullardan
-- tashqarida) ham o'zgarishi mumkin, shuning uchun bu o'zgarishlarni alohida,
-- ACC_ACCOUNT_OBJECTS dagi obyekt bo'yicha taqsimotdan mustaqil kuzatib
-- borish kerak. Kunlik tarix ACC_ACCOUNT_BALANCES_H jadvalida saqlanadi.
-- =====================================================================

-- Create table
create table ACC_ACCOUNT_BALANCES
(
  account_balance_id NUMBER(19) generated by default as identity,
  account_id           NUMBER(19) not null,
  saldo_in             NUMBER(20) default 0 not null,
  saldo_out            NUMBER(20) default 0 not null,
  income               NUMBER(20) default 0 not null,
  expense              NUMBER(20) default 0 not null,
  income_all           NUMBER(20) default 0 not null,
  expense_all          NUMBER(20) default 0 not null,
  sync_date            DATE default SYSDATE not null,
  created_on           DATE default SYSDATE not null,
  created_by           VARCHAR2(50) default USER not null,
  modified_on          DATE,
  modified_by          VARCHAR2(50)
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNT_BALANCES
  is 'Schetning o''ziga tegishli (obyekt bo''yicha taqsimlanmagan) JORIY
   ostatka/oborot holati - BANK ABS dagi SALDO jadvaliga mos ma''lumotlarning
   bizning tizimimizdagi ACC_ACCOUNTS ga bog''langan joriy nusxasi (bitta
   schet = bitta qator). Ayniqsa bank nomiga ochilgan (OWNER_TYPE=B) schetlar
   uchun muhim, chunki ularning ostatkasi BANK ABS orqali to''g''ridan-to''g''ri
   (bizning modullardan tashqarida) ham o''zgarishi mumkin. Har oper-kun
   yopilganda joriy qiymatlar ACC_ACCOUNT_BALANCES_H ga tarix sifatida
   yoziladi.';

-- Add comments to the columns
comment on column ACC_ACCOUNT_BALANCES.account_balance_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_BALANCES.account_id
  is 'Schet, FK -> ACC_ACCOUNTS.ACCOUNT_ID (1:1)';
comment on column ACC_ACCOUNT_BALANCES.saldo_in
  is 'Joriy oper-kun kiruvchi qoldig''i (BANK ABS dan sinxronlangan)';
comment on column ACC_ACCOUNT_BALANCES.saldo_out
  is 'Joriy (hozirgi) qoldiq (BANK ABS dan sinxronlangan)';
comment on column ACC_ACCOUNT_BALANCES.income
  is 'Joriy kundagi kirim';
comment on column ACC_ACCOUNT_BALANCES.expense
  is 'Joriy kundagi chiqim';
comment on column ACC_ACCOUNT_BALANCES.income_all
  is 'Boshidan buyon jami kirim';
comment on column ACC_ACCOUNT_BALANCES.expense_all
  is 'Boshidan buyon jami chiqim';
comment on column ACC_ACCOUNT_BALANCES.sync_date
  is 'Ma''lumot BANK ABS dan so''nggi marta sinxronlangan sana/vaqt';
comment on column ACC_ACCOUNT_BALANCES.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_BALANCES.created_by
  is 'Yozuvni yaratgan foydalanuvchi/servis';
comment on column ACC_ACCOUNT_BALANCES.modified_on
  is 'Yozuv oxirgi marta o''zgartirilgan (sinxronlangan) sana/vaqt';
comment on column ACC_ACCOUNT_BALANCES.modified_by
  is 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi/servis';

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNT_BALANCES
  add constraint ACC_ACCOUNT_BALANCES_PK primary key (ACCOUNT_BALANCE_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_BALANCES
  add constraint ACC_ACCOUNT_BALANCES_U1 unique (ACCOUNT_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_BALANCES
  add constraint ACC_ACCOUNT_BALANCES_F1 foreign key (ACCOUNT_ID)
  references ACC_ACCOUNTS (ACCOUNT_ID);


-- =====================================================================
-- ACC_ACCOUNT_BALANCES_H - ACC_ACCOUNT_BALANCES uchun oper-kunlar bo'yicha
-- tarix (BANK ABS dagi SALDO jadvaliga mos rol).
-- =====================================================================

-- Create table
create table ACC_ACCOUNT_BALANCES_H
(
  account_balance_hist_id NUMBER(19) generated by default as identity,
  account_balance_id        NUMBER(19) not null,
  oper_day                  DATE not null,
  saldo_in                  NUMBER(20) default 0 not null,
  saldo_out                 NUMBER(20) default 0 not null,
  income                    NUMBER(20) default 0 not null,
  expense                   NUMBER(20) default 0 not null,
  income_all                NUMBER(20) default 0 not null,
  expense_all                NUMBER(20) default 0 not null,
  created_on                DATE default SYSDATE not null,
  created_by                VARCHAR2(50) default USER not null
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Add comments to the table
comment on table ACC_ACCOUNT_BALANCES_H
  is 'ACC_ACCOUNT_BALANCES dagi har bir schet uchun o''tgan oper-kunlar
   bo''yicha tarixiy ostatka/oborot yozuvlari (BANK ABS dagi SALDO jadvaliga
   mos rol).';

-- Add comments to the columns
comment on column ACC_ACCOUNT_BALANCES_H.account_balance_hist_id
  is 'Yozuvning unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_BALANCES_H.account_balance_id
  is 'Schet balansi, FK -> ACC_ACCOUNT_BALANCES.ACCOUNT_BALANCE_ID';
comment on column ACC_ACCOUNT_BALANCES_H.oper_day
  is 'Operatsion kun (tarixiy yozuv tegishli bo''lgan oper-kun)';
comment on column ACC_ACCOUNT_BALANCES_H.saldo_in
  is 'Ushbu oper-kundagi kiruvchi qoldiq';
comment on column ACC_ACCOUNT_BALANCES_H.saldo_out
  is 'Ushbu oper-kundagi chiquvchi qoldiq';
comment on column ACC_ACCOUNT_BALANCES_H.income
  is 'Ushbu oper-kundagi kirim';
comment on column ACC_ACCOUNT_BALANCES_H.expense
  is 'Ushbu oper-kundagi chiqim';
comment on column ACC_ACCOUNT_BALANCES_H.income_all
  is 'Ushbu oper-kunga qadar boshidan buyon jami kirim';
comment on column ACC_ACCOUNT_BALANCES_H.expense_all
  is 'Ushbu oper-kunga qadar boshidan buyon jami chiqim';
comment on column ACC_ACCOUNT_BALANCES_H.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_BALANCES_H.created_by
  is 'Yozuvni yaratgan foydalanuvchi/servis';

-- Create/Recreate indexes
create index ACC_ACCOUNT_BALANCES_H_I1 on ACC_ACCOUNT_BALANCES_H (OPER_DAY)
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints
alter table ACC_ACCOUNT_BALANCES_H
  add constraint ACC_ACCOUNT_BALANCES_H_PK primary key (ACCOUNT_BALANCE_HIST_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_BALANCES_H
  add constraint ACC_ACCOUNT_BALANCES_H_U1 unique (ACCOUNT_BALANCE_ID, OPER_DAY)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_BALANCES_H
  add constraint ACC_ACCOUNT_BALANCES_H_F1 foreign key (ACCOUNT_BALANCE_ID)
  references ACC_ACCOUNT_BALANCES (ACCOUNT_BALANCE_ID);
