SET LINESIZE 200
SET PAGESIZE 100
WHENEVER SQLERROR CONTINUE

-- Mahsulot (PF_PRODUCT) parametr qiymatlarini saqlash/oldindan ko'rish
-- jarayonlari. Ikkalasi ham PF_PRODUCT ob'ektiga tegishli (relation_key =
-- product_id), lekin PREVIEW hech narsani bazaga yozmaydi (holat o'zgarmaydi).

-- SAVE_PF_PRODUCT_PARAMS - avvaldan mavjud (SAFARMUROD), bu yerda faqat
-- takroriy ishga tushirish uchun (WHENEVER SQLERROR CONTINUE bilan xavfsiz).
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('SAVE_PF_PRODUCT_PARAMS', 'PF_PRODUCT', 'ROOT', 'A', 'product_id', SYSDATE, 'SAFARMUROD', 'EDITED', 'POST', 'Mahsulot parametr qiymatlarini saqlash');

INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_PRODUCT', 'SAVE_PF_PRODUCT_PARAMS', 'CREATED', 'EDITED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_PRODUCT', 'SAVE_PF_PRODUCT_PARAMS', 'EDITED', 'EDITED', 'N');

INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_PF_PRODUCT_PARAMS_EVT', 'A');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('SAVE_PF_PRODUCT_PARAMS', 'SAVE_PF_PRODUCT_PARAMS_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_PF_PRODUCT_PARAMS', 'Pf_Sm_Api.Save_Product_Parameter_Values', 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_PF_PRODUCT_PARAMS_EVT', 'SAVE_PF_PRODUCT_PARAMS', 1, 'A');

-- PREVIEW_PF_PRODUCT_PARAMS - yangi: FUNCTION turidagi (hisoblanadigan)
-- parametrlarni formadagi joriy (hali saqlanmagan) qiymatlar asosida
-- hisoblab qaytaradi, bazaga yozmaydi (MODEL_* kabi GET, holat o'zgarmaydi).
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('PREVIEW_PF_PRODUCT_PARAMS', 'PF_PRODUCT', 'ROOT', 'A', 'product_id', SYSDATE, 'B.URALOV', NULL, 'GET', 'FUNCTION parametrlarni saqlamasdan hisoblash');

INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('PREVIEW_PF_PRODUCT_PARAMS_EVT', 'A');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('PREVIEW_PF_PRODUCT_PARAMS', 'PREVIEW_PF_PRODUCT_PARAMS_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('PREVIEW_PF_PRODUCT_PARAMS', 'Pf_Sm_Api.Preview_Product_Parameters', 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('PREVIEW_PF_PRODUCT_PARAMS_EVT', 'PREVIEW_PF_PRODUCT_PARAMS', 1, 'A');

COMMIT;

PROMPT === verify ===
SELECT process_code, object_code, relation_key, new_object_state, process_type FROM SM_R_PROCESSES WHERE process_code IN ('SAVE_PF_PRODUCT_PARAMS', 'PREVIEW_PF_PRODUCT_PARAMS');
