SET LINESIZE 200
SET PAGESIZE 100
WHENEVER SQLERROR CONTINUE

INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('PF_PARAMETER', 'ROOT', 'START', 'PF_PARAMETER_SQ', SYSDATE, 'PF_INTEGRATION', 'A');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, PROCESS_TYPE, DESCRIPTION)
VALUES ('MODEL_PF_PARAMETER', 'PF_PARAMETER', 'ROOT', 'A', 'sm_relation_id', SYSDATE, 'PF_INTEGRATION', 'GET', 'Parametr modelini o''qish (edit uchun)');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, PROCESS_TYPE, DESCRIPTION)
VALUES ('CREATE_PF_PARAMETER', 'PF_PARAMETER', 'ROOT', 'A', 'sm_relation_id', SYSDATE, 'PF_INTEGRATION', 'POST', 'Yangi parametr yaratish');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, PROCESS_TYPE, DESCRIPTION)
VALUES ('EDIT_PF_PARAMETER', 'PF_PARAMETER', 'ROOT', 'A', 'sm_relation_id', SYSDATE, 'PF_INTEGRATION', 'POST', 'Parametrni tahrirlash');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, PROCESS_TYPE, DESCRIPTION)
VALUES ('DELETE_PF_PARAMETER', 'PF_PARAMETER', 'ROOT', 'A', 'sm_relation_id', SYSDATE, 'PF_INTEGRATION', 'POST', 'Parametrni o''chirish');

INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_PF_PARAMETER_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_PF_PARAMETER_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_PF_PARAMETER_EVT', 'A');

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_PF_PARAMETER', 'MODEL_PF_PARAMETER_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_PF_PARAMETER', 'SAVE_PF_PARAMETER_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_PF_PARAMETER', 'SAVE_PF_PARAMETER_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_PF_PARAMETER', 'DELETE_PF_PARAMETER_EVT', 1, 'A', 'S');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_PF_PARAMETER', 'Pf_Sm_Api.Model_Parameter', 'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_PF_PARAMETER', 'Pf_Sm_Api.Save_Parameter', 'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_PF_PARAMETER', 'Pf_Sm_Api.Delete_Parameter', 'A');

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_PF_PARAMETER_EVT', 'MODEL_PF_PARAMETER', 1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_PF_PARAMETER_EVT', 'SAVE_PF_PARAMETER', 1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_PF_PARAMETER_EVT', 'DELETE_PF_PARAMETER', 1, 'A');

COMMIT;

PROMPT === verify ===
SELECT process_code, object_code, relation_key, process_type FROM SM_R_PROCESSES WHERE object_code = 'PF_PARAMETER';
SELECT procedure_code, procedure_name FROM SM_R_PROCEDURES WHERE procedure_code LIKE '%PF_PARAMETER%';
