SET LINESIZE 200
SET PAGESIZE 100
WHENEVER SQLERROR CONTINUE

-- PF_VERSION_RULE - PF_PARAMETER'ning haqiqiy bolasi (parent_object_code/
-- parent_relation_key orqali), JSON ichiga yashiringan reference emas.

INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('PF_VERSION_RULE', 'PF_PARAMETER', 'START', 'PF_VERSION_RULE_SQ', SYSDATE, 'B.URALOV', 'A');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('MODEL_PF_VERSION_RULE', 'PF_VERSION_RULE', 'PF_PARAMETER', 'A', 'version_rule_id', 'parameter_id', SYSDATE, 'B.URALOV', NULL, 'GET', 'Qoida modelini o''qish (edit uchun)');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('CREATE_PF_VERSION_RULE', 'PF_VERSION_RULE', 'PF_PARAMETER', 'A', 'version_rule_id', 'parameter_id', SYSDATE, 'B.URALOV', 'CREATED', 'POST', 'Yangi qoida yaratish');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('EDIT_PF_VERSION_RULE', 'PF_VERSION_RULE', 'PF_PARAMETER', 'A', 'version_rule_id', 'parameter_id', SYSDATE, 'B.URALOV', 'EDITED', 'POST', 'Qoidani tahrirlash');
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, NEW_OBJECT_STATE, PROCESS_TYPE, DESCRIPTION)
VALUES ('DELETE_PF_VERSION_RULE', 'PF_VERSION_RULE', 'PF_PARAMETER', 'A', 'version_rule_id', 'parameter_id', SYSDATE, 'B.URALOV', 'DELETED', 'POST', 'Qoidani o''chirish');

INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_VERSION_RULE', 'CREATE_PF_VERSION_RULE', 'START', 'CREATED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_VERSION_RULE', 'EDIT_PF_VERSION_RULE', 'CREATED', 'EDITED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_VERSION_RULE', 'EDIT_PF_VERSION_RULE', 'EDITED', 'EDITED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_VERSION_RULE', 'DELETE_PF_VERSION_RULE', 'CREATED', 'DELETED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('PF_VERSION_RULE', 'DELETE_PF_VERSION_RULE', 'EDITED', 'DELETED', 'N');

INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_PF_VERSION_RULE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_PF_VERSION_RULE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_PF_VERSION_RULE_EVT', 'A');

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_PF_VERSION_RULE', 'MODEL_PF_VERSION_RULE_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_PF_VERSION_RULE', 'SAVE_PF_VERSION_RULE_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_PF_VERSION_RULE', 'SAVE_PF_VERSION_RULE_EVT', 1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_PF_VERSION_RULE', 'DELETE_PF_VERSION_RULE_EVT', 1, 'A', 'S');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_PF_VERSION_RULE', 'Pf_Sm_Api.Model_Version_Rule', 'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_PF_VERSION_RULE', 'Pf_Sm_Api.Save_Version_Rule', 'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_PF_VERSION_RULE', 'Pf_Sm_Api.Delete_Version_Rule', 'A');

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_PF_VERSION_RULE_EVT', 'MODEL_PF_VERSION_RULE', 1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_PF_VERSION_RULE_EVT', 'SAVE_PF_VERSION_RULE', 1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_PF_VERSION_RULE_EVT', 'DELETE_PF_VERSION_RULE', 1, 'A');

COMMIT;

PROMPT === verify ===
SELECT process_code, object_code, parent_object_code, relation_key, parent_relation_key, process_type FROM SM_R_PROCESSES WHERE object_code = 'PF_VERSION_RULE';
SELECT procedure_code, procedure_name FROM SM_R_PROCEDURES WHERE procedure_code LIKE '%PF_VERSION_RULE%';
