CREATE TABLE FILES_H
(
  LOG_ID      NUMBER         NOT NULL,
  FILE_ID     NUMBER(10)     NOT NULL,
  FILE_TOKEN  VARCHAR2(100),
  DOC_TYPE    NUMBER(5)      NOT NULL,
  FILE_NAME   VARCHAR2(100)  NOT NULL,
  BEGIN_DATE  DATE           NOT NULL,
  END_DATE    DATE           NOT NULL,
  STATE       NUMBER(1)      NOT NULL,
  CREATED_BY  NUMBER         NOT NULL,
  CREATED_ON  DATE           NOT NULL,
  MODIFIED_BY NUMBER         NOT NULL,
  MODIFIED_ON DATE           NOT NULL,
  FILE_URL    VARCHAR2(200),
  DESCRIPTION VARCHAR2(1000),
  ACTION      VARCHAR2(1)    NOT NULL,
  ACTION_DATE DATE           NOT NULL,
  CONSTRAINT FILES_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT FILES_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX FILES_H_IX1 ON FILES_H (FILE_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE FILES_H IS 'FILES jadvali bo''yicha o''zgarishlar tarixi (audit)';
COMMENT ON COLUMN FILES_H.LOG_ID IS 'Tarix qatorining ichki identifikatori';
COMMENT ON COLUMN FILES_H.FILE_ID IS 'Qaysi faylga tegishli (FK emas - asosiy qator o''chirilgan bo''lishi mumkin)';
COMMENT ON COLUMN FILES_H.ACTION IS 'I-insert, U-update, D-delete';
COMMENT ON COLUMN FILES_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
