process.success=successPayForm.jsp
process.retry=retryPayForm.jsp

cheque.success=successCheque.jsp
cheque.retry=retryCheque.jsp

letterOfCredit.success=successLC.jsp
letterOfCredit.retry=retryLC.jsp

user.success=crsuccess.jsp
user.retry=eduser.jsp

inCashOrder.success=successICO.jsp
inCashOrder.retry=retryICO.jsp