CREATE OR REPLACE VIEW PF_PRODUCT_PARAMETER_VALUES_V (PRODUCT_ID, VERSION_ID, VERSION_NO, PARAMETER_ID, PARAMETER_CODE, VALUE) AS
SELECT v.PRODUCT_ID,
       pv.VERSION_ID,
       v.VERSION_NO,
       pv.PARAMETER_ID,
       p.CODE AS PARAMETER_CODE,
       pv.VALUE
  FROM PF_PRODUCT_PARAMETER_VALUES pv
  JOIN PF_PRODUCT_VERSIONS v ON v.ID = pv.VERSION_ID
  JOIN PF_R_PARAMETERS p ON p.ID = pv.PARAMETER_ID;
