CREATE OR REPLACE VIEW PF_PRODUCTS_V
("ID", "CODE", "NAME", "CATEGORY_ID", "CATEGORY_NAME", "DELIVERY_TYPE_ID", "DELIVERY_TYPE_NAME", "CREATED_AT", "CURRENT_VERSION_NO", "CURRENT_STATE", "START_DATE", "END_DATE", "VERSION_COUNT") AS
SELECT p.ID,
       p.CODE,
       p.NAME,
       p.CATEGORY_ID,
       c.NAME AS CATEGORY_NAME,
       p.DELIVERY_TYPE_ID,
       dt.NAME AS DELIVERY_TYPE_NAME,
       p.CREATED_ON AS CREATED_AT,
       pv.VERSION_NO AS CURRENT_VERSION_NO,
       pv.STATE AS CURRENT_STATE,
       pv.START_DATE,
       pv.END_DATE,
       (select count(*) from PF_PRODUCT_VERSIONS v2 where v2.PRODUCT_ID = p.ID) AS VERSION_COUNT
  FROM PF_PRODUCTS p
  JOIN PF_R_CATEGORIES_V c ON c.ID = p.CATEGORY_ID
  JOIN PF_R_PRODUCT_DELIVERY_TYPES_V dt ON dt.ID = p.DELIVERY_TYPE_ID
  LEFT JOIN (
       select v.PRODUCT_ID, v.VERSION_NO, v.STATE, v.START_DATE, v.END_DATE
	 from PF_PRODUCT_VERSIONS v
	where v.VERSION_NO = (select max(v2.VERSION_NO) from PF_PRODUCT_VERSIONS v2 where v2.PRODUCT_ID = v.PRODUCT_ID)
       ) pv ON pv.PRODUCT_ID = p.ID
 ORDER BY p.CREATED_ON DESC;
