CREATE OR REPLACE VIEW PF_R_ATTRIBUTES_V AS
SELECT t.ID,
       t.CODE,
       Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => t.ML_NAME_CODE) AS NAME,
       t.SOURCE_TYPE,
       t.MODULE_CODE,
       t.SORT_ORDER,
       (SELECT COUNT(*) FROM PF_R_ATTRIBUTE_CATEGORIES ac WHERE ac.ATTRIBUTE_ID = t.ID) AS CATEGORY_COUNT,
       (SELECT COUNT(*) FROM PF_R_PARAMETERS p WHERE p.ATTRIBUTE_ID = t.ID) AS PARAM_COUNT
  FROM PF_R_ATTRIBUTES t
 ORDER BY t.SORT_ORDER, t.CODE;
