CREATE OR REPLACE VIEW PF_R_ATTRIBUTE_CATEGORIES_V (ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_SORT_ORDER, CATEGORY_ID, CATEGORY_NAME) AS
SELECT ac.ATTRIBUTE_ID,
       Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => a.ML_NAME_CODE) AS ATTRIBUTE_NAME,
       a.SORT_ORDER AS ATTRIBUTE_SORT_ORDER,
       ac.CATEGORY_ID,
       Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => c.ML_NAME_CODE) AS CATEGORY_NAME
  FROM PF_R_ATTRIBUTE_CATEGORIES ac
  JOIN PF_R_ATTRIBUTES a ON a.ID = ac.ATTRIBUTE_ID
  JOIN PF_R_CATEGORIES c ON c.ID = ac.CATEGORY_ID;
