CREATE OR REPLACE VIEW PF_VERSION_RULES_V ("ID", "SCOPE_TYPE", "SCOPE_NAME", "PARAMETER_ID", "PARAMETER_NAME", "RULE_TYPE", "SORT_ORDER", "ERROR_MESSAGE", "CONDITION", "TARGET") AS
SELECT t.ID,
       CASE WHEN t.CATEGORY_ID IS NOT NULL THEN 'CATEGORY' ELSE 'PRODUCT' END AS SCOPE_TYPE,
       COALESCE(
         (SELECT Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => c.ML_NAME_CODE) FROM PF_R_CATEGORIES c WHERE c.ID = t.CATEGORY_ID),
         (SELECT p.NAME FROM PF_PRODUCTS p WHERE p.ID = t.PRODUCT_ID)
       ) AS SCOPE_NAME,
       t.PARAMETER_ID,
       (SELECT Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => pr.ML_NAME_CODE) FROM PF_R_PARAMETERS pr WHERE pr.ID = t.PARAMETER_ID) AS PARAMETER_NAME,
       t.RULE_TYPE,
       t.SORT_ORDER,
       Mll_Core_Api.Get_Label(i_Module_Code => 'PF', i_Message_Code => t.ML_ERROR_CODE) AS ERROR_MESSAGE,
       t.CONDITION,
       t.TARGET
  FROM PF_VERSION_RULES t;
