-- ==========================================================================
-- MPT_PRINT_SETTING - "Shablon sozlamalari" ekrani uchun SM registratsiyasi.
-- Boshqa MPT obyektlaridan farqli - process_type=OPERATION (POST emas):
-- eski, SM'siz yaratilgan MPT_PRINT_SETTINGS qatorlarini tahrirlashda POST
-- SM_OBJECT_NOT_FOUND beradi, OPERATION esa obyekt-tracking qilmaydi.
-- SAVE_PRINT_SETTING ning AFTER_PROCESS_CODE'i = SAVE_SETTING_FILES:
-- asosiy saqlash muvaffaqiyatli bo'lgach, kernel (SM_KERNEL.Run_After_Process)
-- fayl bog'lashni after_process_hash bilan alohida process sifatida yuritadi.
-- ==========================================================================

INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('MPT_PRINT_SETTING', 'ROOT', 'START', 'MPT_PRINT_SETTINGS_S1', SYSDATE, 'MPT_INTEGRATION', 'A');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, BEFORE_PROCESS_CODE, AFTER_PROCESS_CODE, DESCRIPTION, IS_DEAL)
VALUES ('SAVE_PRINT_SETTING', 'MPT_PRINT_SETTING', 'ROOT', 'A', 'setting_id', NULL, SYSDATE, 'MPT_INTEGRATION', 'N', NULL, 'OPERATION', NULL, 'SAVE_SETTING_FILES', 'Chop sozlamasini saqlash (create/edit)', NULL);

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, STATE, RELATION_KEY, PARENT_RELATION_KEY, CREATED_ON, CREATED_DEVELOPER, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, BEFORE_PROCESS_CODE, AFTER_PROCESS_CODE, DESCRIPTION, IS_DEAL)
VALUES ('SAVE_SETTING_FILES', 'MPT_PRINT_SETTING', 'ROOT', 'A', 'setting_id', NULL, SYSDATE, 'MPT_INTEGRATION', 'N', NULL, 'OPERATION', NULL, NULL, 'Chop sozlamasi fayllarini biriktirish (after-process)', NULL);

-- Event master (SM_R_PROCESS_EVENTS.EVENT_CODE bu jadvalga FK) - avval kerak.
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_PRINT_SETTING_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_SETTING_FILES_EVT', 'A');

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE, HOLD_CHECK_PROCEDURE)
VALUES ('SAVE_PRINT_SETTING', 'SAVE_PRINT_SETTING_EVT', 1, 'A', 'S', NULL);

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE, HOLD_CHECK_PROCEDURE)
VALUES ('SAVE_SETTING_FILES', 'SAVE_SETTING_FILES_EVT', 1, 'A', 'S', NULL);

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE)
VALUES ('SAVE_PRINT_SETTING_EVT', 'SAVE_PRINT_SETTING', 1, 'A');

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE)
VALUES ('SAVE_SETTING_FILES_EVT', 'SAVE_SETTING_FILES', 1, 'A');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE)
VALUES ('SAVE_PRINT_SETTING', 'Mpt_Admin_Api.Save_Setting_Sm', 'A');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE)
VALUES ('SAVE_SETTING_FILES', 'Mpt_Admin_Api.Save_Setting_Files_Sm', 'A');

COMMIT;
