INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, ORGANIZATION_LEVEL, NEW_STATE, IS_APPROVE) VALUES ('MPT_GLOBAL_VARIABLE', 'CREATE_GLOBAL_VARIABLE', 'START', NULL, 'A', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, ORGANIZATION_LEVEL, NEW_STATE, IS_APPROVE) VALUES ('MPT_TEMPLATE_TYPE', 'CREATE_TEMPLATE_TYPE', 'START', NULL, 'A', 'N');
