
  CREATE TABLE "MPT_STATES"
   (	"STATE_CODE" VARCHAR2(1) NOT NULL ENABLE,
	"NAME_MLL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	 CONSTRAINT "MPT_STATES_C1" PRIMARY KEY ("STATE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_STATES_CH1" CHECK (State_Code in ('Y', 'N')) ENABLE
   ) ;

