
  CREATE TABLE "MPT_TEMPLATE_TYPES"
   (	"TEMPLATE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TEMPLATE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"MODIFIED_BY" NUMBER(30,0),
	"MODIFIED_ON" DATE,
	"LOCAL_CODE" VARCHAR2(20),
	"BXM_NAME" VARCHAR2(200),
	"MODULE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"CBU_CODE" VARCHAR2(5),
	"SM_RELATION_ID" NUMBER(10,0),
	 CONSTRAINT "MPT_TEMPLATE_TYPES_C1" PRIMARY KEY ("TEMPLATE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_TYPES_CH1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_TYPES_C2" UNIQUE ("SM_RELATION_ID")
  USING INDEX  ENABLE
   ) ;

