
  CREATE TABLE "MPT_TEMPLATE_TYPES_H"
   (	"LOG_ID" NUMBER NOT NULL ENABLE,
	"TEMPLATE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TEMPLATE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"IS_ACTIVE" VARCHAR2(1) NOT NULL ENABLE,
	"CREATED_BY" NUMBER NOT NULL ENABLE,
	"MODIFIED_BY" NUMBER,
	"MODIFIED_ON" DATE,
	"LOCAL_CODE" VARCHAR2(20),
	"BXM_NAME" VARCHAR2(200),
	"MODULE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"CBU_CODE" VARCHAR2(5),
	"SM_RELATION_ID" NUMBER,
	"ACTION" VARCHAR2(1) NOT NULL ENABLE,
	"ACTION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_TYPES_H_C1" CHECK (ACTION IN ('I','U','D')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_TYPES_H_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

