
  CREATE TABLE "MPT_PRINT_HISTORY"
   (	"HISTORY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"TEMPLATE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"MODULE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"LANG_CODE" VARCHAR2(5) NOT NULL ENABLE,
	"PRINTED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"PRINT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"OUTPUT_FORMAT" VARCHAR2(10) NOT NULL ENABLE,
	"RECORD_ID" VARCHAR2(100),
	"INPUT_PARAMS" CLOB,
	"FILE_ID" VARCHAR2(36),
	"VARS_SNAPSHOT" CLOB,
	"QR_CONTENTS" CLOB,
	"STATUS" VARCHAR2(20) NOT NULL ENABLE,
	"ERROR_MESSAGE" VARCHAR2(4000),
	 CONSTRAINT "MPT_PRINT_HISTORY_C1" PRIMARY KEY ("HISTORY_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_HISTORY_CH1" CHECK (OUTPUT_FORMAT IN ('ORIGINAL', 'PDF')) ENABLE,
	 CONSTRAINT "MPT_PRINT_HISTORY_CH2" CHECK (STATUS IN ('SUCCESS', 'FAILED', 'PENDING', 'REPRINTED')) ENABLE
   ) ;

