
  CREATE TABLE "MPT_PRINT_VARIABLES_H"
   (	"LOG_ID" NUMBER NOT NULL ENABLE,
	"VARIABLE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"SCOPE" VARCHAR2(10) NOT NULL ENABLE,
	"MODULE_CODE" VARCHAR2(50),
	"VAR_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"VAR_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"VAR_SOURCE" VARCHAR2(20) NOT NULL ENABLE,
	"VAR_VALUE" VARCHAR2(500),
	"VAR_QUERY" CLOB,
	"DESCRIPTION" CLOB,
	"EXAMPLE_VALUE" VARCHAR2(500),
	"USAGE_NOTE" VARCHAR2(500),
	"NEEDS_TRANSLIT" VARCHAR2(1) NOT NULL ENABLE,
	"IS_REQUIRED" VARCHAR2(1) NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE NOT NULL ENABLE,
	"SM_RELATION_ID" NUMBER(10,0),
	"MODIFIED_BY" NUMBER(30,0),
	"MODIFIED_ON" DATE,
	"ACTION" VARCHAR2(1) NOT NULL ENABLE,
	"ACTION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_H_C1" CHECK (ACTION IN ('I','U','D')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_H_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

COMMENT ON TABLE "MPT_PRINT_VARIABLES_H" IS 'RU: История изменений переменных печати (MPT_PRINT_VARIABLES). UZC: Чоп узгарувчилари (MPT_PRINT_VARIABLES) узгаришлар тарихи. UZ: Chop o''zgaruvchilari (MPT_PRINT_VARIABLES) o''zgarishlar tarixi. EN: Change history of print variables (MPT_PRINT_VARIABLES).';
