
  CREATE TABLE "MPT_PRINT_VARIABLES"
   (	"VARIABLE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"SCOPE" VARCHAR2(10) NOT NULL ENABLE,
	"MODULE_CODE" VARCHAR2(50),
	"VAR_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"VAR_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"VAR_SOURCE" VARCHAR2(20) NOT NULL ENABLE,
	"VAR_VALUE" VARCHAR2(500),
	"VAR_QUERY" CLOB,
	"DESCRIPTION" CLOB,
	"EXAMPLE_VALUE" VARCHAR2(500),
	"USAGE_NOTE" VARCHAR2(500),
	"NEEDS_TRANSLIT" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_REQUIRED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SM_RELATION_ID" NUMBER(10,0),
	"MODIFIED_BY" NUMBER(30,0),
	"MODIFIED_ON" DATE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_C1" PRIMARY KEY ("VARIABLE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_C2" UNIQUE ("MODULE_CODE", "VARIABLE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_CH1" CHECK (SCOPE IN ('GLOBAL', 'MODULE')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_CH2" CHECK (VAR_SOURCE IN ('STATIC', 'DYNAMIC')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_CH3" CHECK (NEEDS_TRANSLIT IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_CH4" CHECK (IS_REQUIRED IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_CH5" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_PRINT_VARIABLES_C3" UNIQUE ("SM_RELATION_ID")
  USING INDEX  ENABLE
   ) ;

