
  CREATE TABLE "MPT_TEMPLATE_CELL_MAPPING"
   (	"MAPPING_ID" NUMBER(19,0) NOT NULL ENABLE,
	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"VARIABLE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"SHEET_NAME" VARCHAR2(50) DEFAULT 'Sheet1' NOT NULL ENABLE,
	"CELL_ADDRESS" VARCHAR2(20) NOT NULL ENABLE,
	"IS_DYNAMIC_ROW" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"DYNAMIC_ROW_PARAM" VARCHAR2(50),
	"IS_RANGE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_MERGED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_TABLE_START" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_C1" PRIMARY KEY ("MAPPING_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_C2" UNIQUE ("GROUP_CODE", "SHEET_NAME", "CELL_ADDRESS")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_CH1" CHECK (IS_DYNAMIC_ROW IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_CH2" CHECK (IS_RANGE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_CH3" CHECK (IS_MERGED IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_CH4" CHECK (IS_TABLE_START IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_CELL_MAPPING_CH5" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE
   ) ;

