
  CREATE TABLE "MPT_PRINT_SETTINGS_H"
   (	"LOG_ID" NUMBER NOT NULL ENABLE,
	"SETTING_ID" NUMBER NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) NOT NULL ENABLE,
	"OPER_DAY" DATE NOT NULL ENABLE,
	"MODIFIED_BY" NUMBER,
	"MODIFIED_ON" DATE,
	"SETTING_NAME" VARCHAR2(200),
	"MODULE_CODE" VARCHAR2(20),
	"TEMPLATE_CODE" VARCHAR2(50),
	"FILE_TYPE" VARCHAR2(10),
	"FILE_FORMAT" VARCHAR2(10),
	"ACTIVATION_DATE" DATE,
	"DESCRIPTION" VARCHAR2(1000),
	"DEACTIVATION_DATE" DATE,
	"OPEN_AS_PDF" VARCHAR2(1) NOT NULL ENABLE,
	"ACTION" VARCHAR2(1) NOT NULL ENABLE,
	"ACTION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_PRINT_SETTINGS_H_CH1" CHECK (ACTION IN ('I','U','D')) ENABLE,
	 CONSTRAINT "MPT_PRINT_SETTINGS_H_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

comment on table Mpt_Print_Settings_H is 'MPT_PRINT_SETTINGS uchun o`zgarishlar tarixi - har bir INSERT/UPDATE/DELETE`dan keyingi qator holati saqlanadi';
comment on column Mpt_Print_Settings_H.Action is 'I=yaratildi, U=ozgartirildi, D=ochirildi';
