
  CREATE TABLE "MPT_VARIABLE_TYPES"
   (	"TYPE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_VARIABLE_TYPES_C1" PRIMARY KEY ("TYPE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_VARIABLE_TYPES_CH1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE
   ) ;

