
  CREATE TABLE "MPT_TRANSLIT_RULE"
   (	"RULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(6,0) NOT NULL ENABLE,
	"LATIN_SRC" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"CYRIL_TGT" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"CASE_MODE" VARCHAR2(1) DEFAULT 'D' NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_TRANSLIT_RULE_C1" PRIMARY KEY ("RULE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TRANSLIT_RULE_C2" UNIQUE ("LATIN_SRC")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TRANSLIT_RULE_CH1" CHECK (CASE_MODE IN ('D', 'A')) ENABLE,
	 CONSTRAINT "MPT_TRANSLIT_RULE_CH2" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE
   ) ;

