
  CREATE TABLE "MPT_TEMPLATE_VAR_MAPPING_DOC"
   (	"MAPPING_ID" NUMBER(19,0) NOT NULL ENABLE,
	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"VARIABLE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"PLACEHOLDER" VARCHAR2(100) NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_VAR_MAPPING_DOC_C1" PRIMARY KEY ("MAPPING_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_VAR_MAPPING_DOC_C2" UNIQUE ("GROUP_CODE", "PLACEHOLDER")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_VAR_MAPPING_DOC_CH1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE
   ) ;

