
  CREATE TABLE "MPT_TEMPLATE_GROUPS"
   (	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"GROUP_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"MODULE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"HISTORY_RETENTION_DAYS" NUMBER(4,0),
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"PRODUCT_TYPE" VARCHAR2(20),
	"TEMPLATE_CODE" VARCHAR2(50),
	"WORKFLOW_STATE" VARCHAR2(20) DEFAULT 'TASDIQLASHDA' NOT NULL ENABLE,
	"UPDATED_BY" NUMBER(30,0),
	"UPDATED_DATE" DATE,
	 CONSTRAINT "MPT_TEMPLATE_GROUPS_CH1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_GROUPS_CH2" CHECK (HISTORY_RETENTION_DAYS > 0) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_GROUPS_C1" PRIMARY KEY ("GROUP_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_GROUPS_CH3" CHECK (PRODUCT_TYPE IN ('KREDIT', 'IPOTEKA', 'KAFILLIK', 'DEPOZIT', 'KASSA',
                             'XALQARO', 'HISOB', 'TERMINAL', 'AKKREDITIV')) ENABLE,
	 CONSTRAINT "MPT_TEMPLATE_GROUPS_CH4" CHECK (WORKFLOW_STATE IN ('AKTIV', 'PASSIV', 'TASDIQLASHDA', 'ARXIVDA', 'BEKOR_QILINGAN')) ENABLE
   ) ;

