
  CREATE TABLE "MPT_ACTIONS"
   (	"ACTION_CODE" VARCHAR2(1) NOT NULL ENABLE,
	"NAME_MLL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CREATED_BY" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_ACTIONS_CH1" CHECK (ACTION_CODE IN ('I','U','D')) ENABLE,
	 CONSTRAINT "MPT_ACTIONS_C1" PRIMARY KEY ("ACTION_CODE")
  USING INDEX  ENABLE
   ) ;

