
  CREATE TABLE "MPT_PRINT_TEMPLATES"
   (	"TEMPLATE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"LANG_CODE" VARCHAR2(5) NOT NULL ENABLE,
	"FILE_ID" VARCHAR2(36) NOT NULL ENABLE,
	"FILE_FORMAT" VARCHAR2(10) NOT NULL ENABLE,
	"PLACEHOLDER_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"VERSION" NUMBER(4,0) DEFAULT 1 NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_C1" PRIMARY KEY ("TEMPLATE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_C2" UNIQUE ("GROUP_CODE", "LANG_CODE", "VERSION")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_CH1" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_CH2" CHECK (VERSION > 0) ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_CH3" CHECK (UPPER(FILE_FORMAT) IN ('DOC', 'DOCX', 'XLSX')) ENABLE,
	 CONSTRAINT "MPT_PRINT_TEMPLATES_CH4" CHECK (UPPER(PLACEHOLDER_TYPE) IN ('SQUARE', 'CELL')) ENABLE
   ) ;

