
  CREATE TABLE "MPT_PRINT_QR_CODES"
   (	"QR_ID" NUMBER(19,0) NOT NULL ENABLE,
	"VARIABLE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"GROUP_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"QR_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"QR_SIZE_MM" NUMBER(3,0) DEFAULT 30 NOT NULL ENABLE,
	"QR_CONTENT_TEMPLATE" CLOB,
	"QR_POSITION" VARCHAR2(20) NOT NULL ENABLE,
	"CELL_ADDRESS" VARCHAR2(20),
	"IS_EVERY_PAGE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"ERROR_CORRECTION" VARCHAR2(1) DEFAULT 'M' NOT NULL ENABLE,
	"IS_ACTIVE" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED_BY" NUMBER(30,0) NOT NULL ENABLE,
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_C1" PRIMARY KEY ("QR_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_C2" UNIQUE ("VARIABLE_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_CH1" CHECK (QR_SIZE_MM IN (20, 25, 30, 40, 50)) ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_CH2" CHECK (QR_POSITION IN ('PLACEHOLDER', 'FOOTER', 'HEADER', 'CELL')) ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_CH3" CHECK (IS_EVERY_PAGE IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_CH4" CHECK (ERROR_CORRECTION IN ('L', 'M', 'Q', 'H')) ENABLE,
	 CONSTRAINT "MPT_PRINT_QR_CODES_CH5" CHECK (IS_ACTIVE IN ('Y', 'N')) ENABLE
   ) ;

