--------------------------------------------------------------------------------
-- "Тип счёта" (ACC_ACCOUNT_TYPE) va uning дочерняя запись (ACC_ACCOUNT_TYPE_CLIENT)
-- obyektlarini Core_Api / Sm_Kernel ish-jarayon (workflow) dvigateliga ro'yxatga
-- olish. Naqsh: PF_CATEGORY / PF_ATTRIBUTE bilan bir xil (SM_R_OBJECTS,
-- SM_R_PROCESSES, SM_R_EVENTS, SM_R_PROCESS_EVENTS, SM_R_EVENT_PROCEDURES,
-- SM_R_PROCEDURES, SM_R_TRANZITIONS).
--------------------------------------------------------------------------------
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

--================================================================================
-- 1) SM_R_OBJECTS
--================================================================================
INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('ACC_ACCOUNT_TYPE', 'ROOT', 'START', 'ACC_ACCOUNT_TYPES_SQ', SYSDATE, 'ABDUQODIR', 'A');

INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'ROOT', 'START', 'ACC_ACCOUNT_TYPE_CLIENTS_SQ', SYSDATE, 'ABDUQODIR', 'A');

--================================================================================
-- 2) SM_R_PROCESSES
-- Diqqat: PARENT_OBJECT_CODE ustuni ham to'ldirilishi shart - Sm_Kernel.Set_Method
-- obyektni aynan shu ustundagi qiymat orqali qidiradi (Sm_Util.Get_r_Object).
--================================================================================
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('MODEL_ACC_ACCOUNT_TYPE', 'ACC_ACCOUNT_TYPE', 'ROOT', 'account_type_id', 'A', 'Y', NULL, 'GET', NULL, 'Тип счёта модели ni o''qish (edit uchun)', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('CREATE_ACC_ACCOUNT_TYPE', 'ACC_ACCOUNT_TYPE', 'ROOT', 'account_type_id', 'A', 'Y', 'CREATED', 'POST', 'Y', 'Yangi тип счёта yaratish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('EDIT_ACC_ACCOUNT_TYPE', 'ACC_ACCOUNT_TYPE', 'ROOT', 'account_type_id', 'A', 'Y', 'EDITED', 'POST', NULL, 'Тип счёта ni tahrirlash', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('DELETE_ACC_ACCOUNT_TYPE', 'ACC_ACCOUNT_TYPE', 'ROOT', 'account_type_id', 'A', 'Y', 'DELETED', 'POST', NULL, 'Тип счёта ni o''chirish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('MODEL_ACC_ACCOUNT_TYPE_CLIENT', 'ACC_ACCOUNT_TYPE_CLIENT', 'ROOT', 'account_type_client_id', 'A', 'Y', NULL, 'GET', NULL, 'Дочерняя запись modelini o''qish (edit uchun)', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('CREATE_ACC_ACCOUNT_TYPE_CLIENT', 'ACC_ACCOUNT_TYPE_CLIENT', 'ROOT', 'account_type_client_id', 'A', 'Y', 'CREATED', 'POST', NULL, 'Yangi дочерняя запись yaratish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('EDIT_ACC_ACCOUNT_TYPE_CLIENT', 'ACC_ACCOUNT_TYPE_CLIENT', 'ROOT', 'account_type_client_id', 'A', 'Y', 'EDITED', 'POST', NULL, 'Дочерняя запись ni tahrirlash', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('DELETE_ACC_ACCOUNT_TYPE_CLIENT', 'ACC_ACCOUNT_TYPE_CLIENT', 'ROOT', 'account_type_client_id', 'A', 'Y', 'DELETED', 'POST', NULL, 'Дочерняя запись ni o''chirish', SYSDATE, 'ABDUQODIR');

--================================================================================
-- 3) SM_R_EVENTS (voqealar lug'ati - SM_R_PROCESS_EVENTS.EVENT_CODE shu yerga FK)
--================================================================================
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_CLIENT_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE_CLIENT_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_CLIENT_EVT', 'A');

--================================================================================
-- 4) SM_R_PROCESS_EVENTS
--================================================================================
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_ACC_ACCOUNT_TYPE',  'MODEL_ACC_ACCOUNT_TYPE_EVT',  1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_ACC_ACCOUNT_TYPE', 'SAVE_ACC_ACCOUNT_TYPE_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_ACC_ACCOUNT_TYPE',   'SAVE_ACC_ACCOUNT_TYPE_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_ACC_ACCOUNT_TYPE', 'DELETE_ACC_ACCOUNT_TYPE_EVT', 1, 'A', 'S');

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_CLIENT',  'MODEL_ACC_ACCOUNT_TYPE_CLIENT_EVT',  1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_ACC_ACCOUNT_TYPE_CLIENT', 'SAVE_ACC_ACCOUNT_TYPE_CLIENT_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_ACC_ACCOUNT_TYPE_CLIENT',   'SAVE_ACC_ACCOUNT_TYPE_CLIENT_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_CLIENT', 'DELETE_ACC_ACCOUNT_TYPE_CLIENT_EVT', 1, 'A', 'S');

--================================================================================
-- 5) SM_R_EVENT_PROCEDURES
--================================================================================
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_EVT',  'MODEL_ACC_ACCOUNT_TYPE',  1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE_EVT',   'SAVE_ACC_ACCOUNT_TYPE',   1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_EVT', 'DELETE_ACC_ACCOUNT_TYPE', 1, 'A');

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_CLIENT_EVT',  'MODEL_ACC_ACCOUNT_TYPE_CLIENT',  1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE_CLIENT_EVT',   'SAVE_ACC_ACCOUNT_TYPE_CLIENT',   1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_CLIENT_EVT', 'DELETE_ACC_ACCOUNT_TYPE_CLIENT', 1, 'A');

--================================================================================
-- 6) SM_R_PROCEDURES
--================================================================================
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE',  'Acc_Sm_Api.Model_Account_Type',  'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE',   'Acc_Sm_Api.Save_Account_Type',   'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE', 'Acc_Sm_Api.Delete_Account_Type', 'A');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_ACC_ACCOUNT_TYPE_CLIENT',  'Acc_Sm_Api.Model_Account_Type_Client',  'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_ACC_ACCOUNT_TYPE_CLIENT',   'Acc_Sm_Api.Save_Account_Type_Client',   'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_ACC_ACCOUNT_TYPE_CLIENT', 'Acc_Sm_Api.Delete_Account_Type_Client', 'A');

--================================================================================
-- 7) SM_R_TRANZITIONS (holat o'tishlari)
--================================================================================
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE', 'CREATE_ACC_ACCOUNT_TYPE', 'START',   'CREATED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE', 'EDIT_ACC_ACCOUNT_TYPE',   'CREATED', 'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE', 'EDIT_ACC_ACCOUNT_TYPE',   'EDITED',  'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE', 'DELETE_ACC_ACCOUNT_TYPE', 'CREATED', 'DELETED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE', 'DELETE_ACC_ACCOUNT_TYPE', 'EDITED',  'DELETED', 'N');

INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'CREATE_ACC_ACCOUNT_TYPE_CLIENT', 'START',   'CREATED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'EDIT_ACC_ACCOUNT_TYPE_CLIENT',   'CREATED', 'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'EDIT_ACC_ACCOUNT_TYPE_CLIENT',   'EDITED',  'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'DELETE_ACC_ACCOUNT_TYPE_CLIENT', 'CREATED', 'DELETED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_TYPE_CLIENT', 'DELETE_ACC_ACCOUNT_TYPE_CLIENT', 'EDITED',  'DELETED', 'N');

COMMIT;
