--------------------------------------------------------------------------------
-- "Хисоб рақамлар" (ACC_ACCOUNT) va uning дочерняя запись (ACC_ACCOUNT_MODULE)
-- obyektlarini Core_Api / Sm_Kernel ish-jarayon (workflow) dvigateliga ro'yxatga
-- olish. Naqsh: ACC_ACCOUNT_TYPE / ACC_ACCOUNT_TYPE_CLIENT bilan bir xil
-- (SM_R_OBJECTS, SM_R_PROCESSES, SM_R_EVENTS, SM_R_PROCESS_EVENTS,
-- SM_R_EVENT_PROCEDURES, SM_R_PROCEDURES, SM_R_TRANZITIONS).
-- MUHIM: kompilyatsiyadan oldin NLS_LANG=AMERICAN_AMERICA.AL32UTF8 o'rnating.
--------------------------------------------------------------------------------
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

--================================================================================
-- 1) SM_R_OBJECTS
--================================================================================
INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('ACC_ACCOUNT', 'ROOT', 'START', 'ACC_ACCOUNTS_SQ', SYSDATE, 'ABDUQODIR', 'A');

INSERT INTO SM_R_OBJECTS (OBJECT_CODE, PARENT_OBJECT_CODE, INITIAL_STATE, SEQUENCE_GETTER, CREATED_ON, CREATED_DEVELOPER, STATE)
VALUES ('ACC_ACCOUNT_MODULE', 'ROOT', 'START', 'ACC_ACCOUNT_MODULES_SQ', SYSDATE, 'ABDUQODIR', 'A');

--================================================================================
-- 2) SM_R_PROCESSES
-- Diqqat: PARENT_OBJECT_CODE ustuni ham to'ldirilishi shart - Sm_Kernel.Set_Method
-- obyektni aynan shu ustundagi qiymat orqali qidiradi (Sm_Util.Get_r_Object).
--================================================================================
INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('MODEL_ACC_ACCOUNT', 'ACC_ACCOUNT', 'ROOT', 'account_id', 'A', 'Y', NULL, 'GET', NULL, 'Хисоб рақами модели ni o''qish (edit uchun)', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('CREATE_ACC_ACCOUNT', 'ACC_ACCOUNT', 'ROOT', 'account_id', 'A', 'Y', 'CREATED', 'POST', 'Y', 'Yangi хисоб рақами yaratish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('EDIT_ACC_ACCOUNT', 'ACC_ACCOUNT', 'ROOT', 'account_id', 'A', 'Y', 'EDITED', 'POST', NULL, 'Хисоб рақами ni tahrirlash', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('DELETE_ACC_ACCOUNT', 'ACC_ACCOUNT', 'ROOT', 'account_id', 'A', 'Y', 'DELETED', 'POST', NULL, 'Хисоб рақами ni o''chirish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('MODEL_ACC_ACCOUNT_MODULE', 'ACC_ACCOUNT_MODULE', 'ROOT', 'account_module_id', 'A', 'Y', NULL, 'GET', NULL, 'Дочерняя запись modelini o''qish (edit uchun)', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('CREATE_ACC_ACCOUNT_MODULE', 'ACC_ACCOUNT_MODULE', 'ROOT', 'account_module_id', 'A', 'Y', 'CREATED', 'POST', NULL, 'Yangi дочерняя запись yaratish', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('EDIT_ACC_ACCOUNT_MODULE', 'ACC_ACCOUNT_MODULE', 'ROOT', 'account_module_id', 'A', 'Y', 'EDITED', 'POST', NULL, 'Дочерняя запись ni tahrirlash', SYSDATE, 'ABDUQODIR');

INSERT INTO SM_R_PROCESSES (PROCESS_CODE, OBJECT_CODE, PARENT_OBJECT_CODE, RELATION_KEY, STATE, SET_LOG, NEW_OBJECT_STATE, PROCESS_TYPE, IS_DEAL, DESCRIPTION, CREATED_ON, CREATED_DEVELOPER)
VALUES ('DELETE_ACC_ACCOUNT_MODULE', 'ACC_ACCOUNT_MODULE', 'ROOT', 'account_module_id', 'A', 'Y', 'DELETED', 'POST', NULL, 'Дочерняя запись ni o''chirish', SYSDATE, 'ABDUQODIR');

--================================================================================
-- 3) SM_R_EVENTS (voqealar lug'ati - SM_R_PROCESS_EVENTS.EVENT_CODE shu yerga FK)
--================================================================================
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_ACC_ACCOUNT_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_ACC_ACCOUNT_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_ACC_ACCOUNT_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('MODEL_ACC_ACCOUNT_MODULE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('SAVE_ACC_ACCOUNT_MODULE_EVT', 'A');
INSERT INTO SM_R_EVENTS (EVENT_CODE, STATE) VALUES ('DELETE_ACC_ACCOUNT_MODULE_EVT', 'A');

--================================================================================
-- 4) SM_R_PROCESS_EVENTS
--================================================================================
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_ACC_ACCOUNT',  'MODEL_ACC_ACCOUNT_EVT',  1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_ACC_ACCOUNT', 'SAVE_ACC_ACCOUNT_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_ACC_ACCOUNT',   'SAVE_ACC_ACCOUNT_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_ACC_ACCOUNT', 'DELETE_ACC_ACCOUNT_EVT', 1, 'A', 'S');

INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('MODEL_ACC_ACCOUNT_MODULE',  'MODEL_ACC_ACCOUNT_MODULE_EVT',  1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('CREATE_ACC_ACCOUNT_MODULE', 'SAVE_ACC_ACCOUNT_MODULE_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('EDIT_ACC_ACCOUNT_MODULE',   'SAVE_ACC_ACCOUNT_MODULE_EVT',   1, 'A', 'S');
INSERT INTO SM_R_PROCESS_EVENTS (PROCESS_CODE, EVENT_CODE, ORDER_BY, STATE, EXECUTION_MODE) VALUES ('DELETE_ACC_ACCOUNT_MODULE', 'DELETE_ACC_ACCOUNT_MODULE_EVT', 1, 'A', 'S');

--================================================================================
-- 5) SM_R_EVENT_PROCEDURES
--================================================================================
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_ACC_ACCOUNT_EVT',  'MODEL_ACC_ACCOUNT',  1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_ACC_ACCOUNT_EVT',   'SAVE_ACC_ACCOUNT',   1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_ACC_ACCOUNT_EVT', 'DELETE_ACC_ACCOUNT', 1, 'A');

INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('MODEL_ACC_ACCOUNT_MODULE_EVT',  'MODEL_ACC_ACCOUNT_MODULE',  1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('SAVE_ACC_ACCOUNT_MODULE_EVT',   'SAVE_ACC_ACCOUNT_MODULE',   1, 'A');
INSERT INTO SM_R_EVENT_PROCEDURES (EVENT_CODE, PROCEDURE_CODE, ORDER_BY, STATE) VALUES ('DELETE_ACC_ACCOUNT_MODULE_EVT', 'DELETE_ACC_ACCOUNT_MODULE', 1, 'A');

--================================================================================
-- 6) SM_R_PROCEDURES
--================================================================================
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_ACC_ACCOUNT',  'Acc_Sm_Api.Model_Account',  'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_ACC_ACCOUNT',   'Acc_Sm_Api.Save_Account',   'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_ACC_ACCOUNT', 'Acc_Sm_Api.Delete_Account', 'A');

INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('MODEL_ACC_ACCOUNT_MODULE',  'Acc_Sm_Api.Model_Account_Module',  'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('SAVE_ACC_ACCOUNT_MODULE',   'Acc_Sm_Api.Save_Account_Module',   'A');
INSERT INTO SM_R_PROCEDURES (PROCEDURE_CODE, PROCEDURE_NAME, STATE) VALUES ('DELETE_ACC_ACCOUNT_MODULE', 'Acc_Sm_Api.Delete_Account_Module', 'A');

--================================================================================
-- 7) SM_R_TRANZITIONS (holat o'tishlari)
--================================================================================
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT', 'CREATE_ACC_ACCOUNT', 'START',   'CREATED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT', 'EDIT_ACC_ACCOUNT',   'CREATED', 'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT', 'EDIT_ACC_ACCOUNT',   'EDITED',  'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT', 'DELETE_ACC_ACCOUNT', 'CREATED', 'DELETED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT', 'DELETE_ACC_ACCOUNT', 'EDITED',  'DELETED', 'N');

INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_MODULE', 'CREATE_ACC_ACCOUNT_MODULE', 'START',   'CREATED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_MODULE', 'EDIT_ACC_ACCOUNT_MODULE',   'CREATED', 'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_MODULE', 'EDIT_ACC_ACCOUNT_MODULE',   'EDITED',  'EDITED',  'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_MODULE', 'DELETE_ACC_ACCOUNT_MODULE', 'CREATED', 'DELETED', 'N');
INSERT INTO SM_R_TRANZITIONS (OBJECT_CODE, PROCESS_CODE, CURRENT_STATE, NEW_STATE, IS_APPROVE) VALUES ('ACC_ACCOUNT_MODULE', 'DELETE_ACC_ACCOUNT_MODULE', 'EDITED',  'DELETED', 'N');

COMMIT;
