-- Create table
create table ACC_ACCOUNT_TYPE_CLIENTS
(
  account_type_client_id NUMBER(19) generated by default as identity,
  account_type_id        NUMBER(19) not null,
  client_type            VARCHAR2(1) not null,
  state                  VARCHAR2(1) default 'A' not null,
  code_coa               VARCHAR2(20) not null,
  currency_code          VARCHAR2(5),
  created_on             DATE default SYSDATE not null,
  created_by             VARCHAR2(50) default USER not null,
  modified_on            DATE,
  modified_by            VARCHAR2(50),
  account_term_type      VARCHAR2(10),
  subject_type           VARCHAR2(5)
)
tablespace CORE_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Add comments to the table 
comment on table ACC_ACCOUNT_TYPE_CLIENTS
  is '"“ËÔ Ò˜∏Ú‡" satrini ochganda ko''rinadigan dochernie zapisi (“ËÔ ÍÎËÂÌÚ‡ /
    Ó‰˚ COA / ¬‡Î˛Ú‡). Bitta "“ËÔ Ò˜∏Ú‡" yozuviga bir nechta dochernie zapisi
   biriktirilishi mumkin (1:N) - jadvalda "ƒÓ˜ÂÌËı Á‡ÔËÒÂÈ" ustunida sanaladi.';
-- Add comments to the columns 
comment on column ACC_ACCOUNT_TYPE_CLIENTS.account_type_client_id
  is 'Dochernie zapisi unikal identifikatori (PK)';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.account_type_id
  is 'Ota "–¢–∏–ø —Å—á—ë—Ç–∞" yozuviga FK -> ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.client_type
  is '–¢–∏–ø –∫–ª–∏–µ–Ω—Ç–∞: C ‚Äî –ö–ª–∏–µ–Ω—Ç, B ‚Äî bank';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.state
  is 'Holati: A ‚Äî –ê–∫—Ç–∏–≤, P ‚Äî –ü–∞—Å—Å–∏–≤';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.code_coa
  is '–ö–æ–¥—ã COA (–ë–∞–ª–∞–Ω—Å –∫–æ–¥) ‚Äî majburiy, masalan "20406"';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.currency_code
  is '–í–∞–ª—é—Ç–∞ kodi (masalan UZS/USD/EUR); "*" qiymati barcha valyutalar uchun mosligini bildiradi ("* ‚Äî –ø–æ–¥—Ö–æ–¥–∏—Ç –¥–ª—è –≤—Å–µ—Ö")';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.created_on
  is 'Yozuv yaratilgan sana/vaqt';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.created_by
  is 'Yozuvni yaratgan foydalanuvchi (operator) login';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.modified_on
  is 'Yozuv oxirgi marta o''zgartirilgan sana/vaqt';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.modified_by
  is 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi (operator) login';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.account_term_type
  is 'Schet muddati: uzoq muddatli yoki qisqa muddatli. (Uzoq or Qisqa)';
comment on column ACC_ACCOUNT_TYPE_CLIENTS.subject_type
  is 'Phys, Jur, IP   Klientning tipi';
-- Create/Recreate primary, unique and foreign key constraints 
alter table ACC_ACCOUNT_TYPE_CLIENTS
  add constraint ACC_ACCOUNT_TYPE_CLIENTS_PK primary key (ACCOUNT_TYPE_CLIENT_ID)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_TYPE_CLIENTS
  add constraint ACC_ACCOUNT_TYPE_CLIENTS_U1 unique (ACCOUNT_TYPE_ID, CODE_COA)
  using index
  tablespace CORE_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACC_ACCOUNT_TYPE_CLIENTS
  add constraint ACC_ACCOUNT_TYPE_CLIENTS_F1 foreign key (ACCOUNT_TYPE_ID)
  references ACC_ACCOUNT_TYPES (ACCOUNT_TYPE_ID) on delete cascade;
-- Create/Recreate check constraints 
alter table ACC_ACCOUNT_TYPE_CLIENTS
  add constraint ACC_ACCOUNT_TYPE_CLIENTS_C1
  check (CLIENT_TYPE IN ('C','B'));
alter table ACC_ACCOUNT_TYPE_CLIENTS
  add constraint ACC_ACCOUNT_TYPE_CLIENTS_C2
  check (STATE IN ('A','P'));
