insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('CREDIT_LINE', 1, 3, 2, 1);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('TRANCHE', 3, 1, 4, 1);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('TRANCHE', 4, 3, 6, 2);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('BOOKING', 1, 2, 2, 1);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('BOOKING', 2, 3, 3, 2);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('TRANCHE_CARD', 3, 2, 4, 1);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('TRANCHE_CARD', 4, 3, 6, 2);

insert into SM_ACTION_ROUTES (OBJECT_CODE, CURR_STATE_ID, ACTION_ID, NEW_STATE_ID, ORDER_NUM)
values ('TC_RESOURCE', 1, 3, 3, 1);

commit;
