INSERT INTO MPT_ACTIONS (ACTION_CODE, NAME_MLL_CODE, CREATED_BY, CREATED_DATE) VALUES ('D', 'MPT_ACTION_DELETE', 1, TO_DATE('2026-07-30 11:51:26','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MPT_ACTIONS (ACTION_CODE, NAME_MLL_CODE, CREATED_BY, CREATED_DATE) VALUES ('I', 'MPT_ACTION_INSERT', 1, TO_DATE('2026-07-30 11:51:26','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO MPT_ACTIONS (ACTION_CODE, NAME_MLL_CODE, CREATED_BY, CREATED_DATE) VALUES ('U', 'MPT_ACTION_UPDATE', 1, TO_DATE('2026-07-30 11:51:26','YYYY-MM-DD HH24:MI:SS'));
