
  ALTER TABLE "MPT_TEMPLATE_TYPE_VARS" ADD CONSTRAINT "MPT_TEMPLATE_TYPE_VARS_F1" FOREIGN KEY ("TEMPLATE_CODE")
	  REFERENCES "MPT_TEMPLATE_TYPES" ("TEMPLATE_CODE") ENABLE;

  ALTER TABLE "MPT_TEMPLATE_TYPE_VARS" ADD CONSTRAINT "MPT_TEMPLATE_TYPE_VARS_F2" FOREIGN KEY ("VARIABLE_CODE")
	  REFERENCES "MPT_PRINT_VARIABLES" ("VARIABLE_CODE") ENABLE;
