--------------------------------------------------------------------------------
-- ACC moduli obyektlariga ilova (Tomcat) UAPP sxemasidan foydalanish huquqini
-- berish: SELECT grantlar + UAPP sxemasida private synonymlar.
-- Buni CORE sxemasi (core/core) ostidan emas, balki UAPP sxemasi (uapp/uapp)
-- ostidan ishga tushirish kerak (synonym o'z sxemangizda yaratiladi).
--------------------------------------------------------------------------------

-- 1) Grantlar (core/core ostidan ishga tushiriladi)
-- Diqqat: JSP'lar hech qachon to'g'ridan-to'g'ri jadvalga emas, faqat view'ga
-- kirishi kerak - shuning uchun ACC_R_MODULES (jadval) uchun emas,
-- ACC_R_MODULES_V (view) uchun grant beriladi.
GRANT SELECT ON CORE.ACC_R_MODULES_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNT_TYPES_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNT_TYPE_CLIENTS_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNT_TYPE_HISTORY_V TO UAPP;
GRANT SELECT ON CORE.ACC_R_CLASS_CATALOG_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNTS_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNT_MODULES_V TO UAPP;
GRANT SELECT ON CORE.ACC_ACCOUNT_BALANCES_V TO UAPP;
GRANT SELECT ON CORE.ABS_BRANCHES_V TO UAPP;
GRANT SELECT ON CORE.SM_R_OBJECTS_V TO UAPP;
GRANT EXECUTE ON CORE.ACC_SM_API TO UAPP;

-- 2) Synonymlar (uapp/uapp ostidan ishga tushiriladi)
CREATE SYNONYM ACC_R_MODULES_V FOR CORE.ACC_R_MODULES_V;
CREATE SYNONYM ACC_ACCOUNT_TYPES_V FOR CORE.ACC_ACCOUNT_TYPES_V;
CREATE SYNONYM ACC_ACCOUNT_TYPE_CLIENTS_V FOR CORE.ACC_ACCOUNT_TYPE_CLIENTS_V;
CREATE SYNONYM ACC_ACCOUNT_TYPE_HISTORY_V FOR CORE.ACC_ACCOUNT_TYPE_HISTORY_V;
CREATE SYNONYM ACC_R_CLASS_CATALOG_V FOR CORE.ACC_R_CLASS_CATALOG_V;
CREATE SYNONYM ACC_ACCOUNTS_V FOR CORE.ACC_ACCOUNTS_V;
CREATE SYNONYM ACC_ACCOUNT_MODULES_V FOR CORE.ACC_ACCOUNT_MODULES_V;
CREATE SYNONYM ACC_ACCOUNT_BALANCES_V FOR CORE.ACC_ACCOUNT_BALANCES_V;
CREATE SYNONYM ABS_BRANCHES_V FOR CORE.ABS_BRANCHES_V;
CREATE SYNONYM SM_R_OBJECTS_V FOR CORE.SM_R_OBJECTS_V;
CREATE SYNONYM ACC_SM_API FOR CORE.ACC_SM_API;
