# connection to MUNIS service
munis.service.url=http://10.0.50.53:80/cb-munis/wService
munis.service.timeout=5

# connection to AFR service
afr.service.url=http://192.168.1.2/afrmunis/client/index.php

# thread quantity
auth.service.quantity=20

# connection to DB oracle
db.url=jdbc:oracle:thin:@192.168.1.1:1521:iabs
db.username=iabs
db.password=iabs