CREATE OR REPLACE VIEW ESBIN_R_USER_METHODS_GRID_V (USER_ID, METHOD_CODE, METHOD_CODE_TXT, NAME, REQUEST_TYPE, SYNCHRONIZE_TYPE, GRANTED) AS
SELECT pu.USER_ID, m.METHOD_CODE, m.METHOD_CODE,  m.NAME, m.REQUEST_TYPE, m.SYNCHRONIZE_TYPE,
       CASE WHEN r.USER_ID IS NOT NULL THEN 1 ELSE 0 END
  FROM ESBIN_R_PARTNER_USERS pu
  CROSS JOIN ESBIN_R_METHODS m
  LEFT JOIN ESBIN_R_USER_METHOD_REL r
         ON r.USER_ID = pu.USER_ID AND r.METHOD_CODE = m.METHOD_CODE AND r.STATE = 'A'
 WHERE m.STATE = 'A';
