CREATE OR REPLACE VIEW ESBIN_R_PARTNER_USERS_V (PARTNER_CODE, PARTNER_NAME, USER_ID, USER_NAME, STATE) AS
SELECT pu.PARTNER_CODE, p.NAME AS PARTNER_NAME, pu.USER_ID, u.NAME AS USER_NAME, pu.STATE
  FROM ESBIN_R_PARTNER_USERS pu
  JOIN ESBIN_R_PARTNERS p ON p.PARTNER_CODE = pu.PARTNER_CODE
  JOIN CORE_USERS u ON u.USER_ID = pu.USER_ID;
