CREATE OR REPLACE VIEW ESBIN_REQUESTS_V
(
  ID, EXT_REQUEST_ID, PARTNER_CODE, PARTNER_NAME, USER_ID, USER_NAME,
  METHOD_CODE, METHOD_NAME, STATE, STATE_LABEL, SYNC_TYPE, CREATED_ON, STARTED_ON,
  FINISHED_ON, DURATION_MS, IP_ADDRESS
) AS
SELECT r.ID, r.EXT_REQUEST_ID, r.PARTNER_CODE, p.NAME AS PARTNER_NAME, r.USER_ID, u.NAME AS USER_NAME,
       r.METHOD_CODE, m.NAME AS METHOD_NAME, r.STATE,
       Mll_Core_Api.Get_Label(i_Module_Code => 'ESBIN', i_Message_Code => 'ESBIN_STATE_' || r.STATE) AS STATE_LABEL,
       r.SYNC_TYPE, r.CREATED_ON, r.STARTED_ON,
       r.FINISHED_ON, r.DURATION_MS, r.IP_ADDRESS
  FROM ESBIN_REQUESTS r
  JOIN ESBIN_R_PARTNERS p ON p.PARTNER_CODE = r.PARTNER_CODE
  JOIN CORE_USERS u ON u.USER_ID = r.USER_ID
  JOIN ESBIN_R_METHODS m ON m.METHOD_CODE = r.METHOD_CODE;
