CREATE TABLE ESBIN_R_USER_METHOD_REL
(
  USER_ID     NUMBER        NOT NULL,
  METHOD_CODE VARCHAR2(100) NOT NULL,
  STATE       VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  CONSTRAINT ESBIN_R_USER_METHOD_REL_PK PRIMARY KEY (USER_ID, METHOD_CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_USER_METHOD_REL_FK1 FOREIGN KEY (USER_ID) REFERENCES CORE_USERS (USER_ID),
  CONSTRAINT ESBIN_R_USER_METHOD_REL_FK2 FOREIGN KEY (METHOD_CODE) REFERENCES ESBIN_R_METHODS (METHOD_CODE),
  CONSTRAINT ESBIN_R_USER_METHOD_REL_C1 CHECK (STATE IN ('A', 'P'))
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_R_USER_METHOD_REL_IX1 ON ESBIN_R_USER_METHOD_REL (METHOD_CODE) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_R_USER_METHOD_REL IS 'Qaysi texnik user qaysi ESBIN methodini chaqira olishi (dostup) - alohida boshqariladi, CORE button/menu tizimiga bog''lanmaydi (process_code''lar buttonga bog''lanmagan bo''lishi mumkin)';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL.USER_ID IS 'CORE_USERS.USER_ID';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL.METHOD_CODE IS 'ESBIN_R_METHODS.METHOD_CODE';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL.STATE IS 'A - active, P - passive';
