CREATE TABLE ESBIN_REQUEST_DETAILS
(
  REQUEST_ID NUMBER NOT NULL,
  REQUEST    CLOB,
  RESPONSE   CLOB,
  CREATED_ON DATE   DEFAULT SYSDATE NOT NULL,
  CONSTRAINT ESBIN_REQUEST_DETAILS_PK PRIMARY KEY (REQUEST_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_REQUEST_DETAILS_FK1 FOREIGN KEY (REQUEST_ID) REFERENCES ESBIN_REQUESTS (ID)
) TABLESPACE CORE_DATA;

COMMENT ON TABLE ESBIN_REQUEST_DETAILS IS 'ESBIN''ning mustaqil to''liq request/response audit-logi - SM''ning o''z logidan qat''iy nazar, har doim (ADD_LOG=Y bo''lganda) yoziladi, avtonom tranzaksiyada';
COMMENT ON COLUMN ESBIN_REQUEST_DETAILS.REQUEST_ID IS 'ESBIN_REQUESTS.ID';
COMMENT ON COLUMN ESBIN_REQUEST_DETAILS.REQUEST IS 'Partnerdan kelgan xom so''rov (JSON)';
COMMENT ON COLUMN ESBIN_REQUEST_DETAILS.RESPONSE IS 'Partnerga qaytarilgan xom javob (JSON)';
