CREATE TABLE ESBIN_R_METHODS_H
(
  LOG_ID           NUMBER        NOT NULL,
  METHOD_CODE      VARCHAR2(100) NOT NULL,
  NAME             VARCHAR2(500),
  PROCESS_CODE     VARCHAR2(100),
  REQUEST_TYPE     VARCHAR2(10),
  SYNCHRONIZE_TYPE VARCHAR2(1),
  RESULT_FUNCTION  VARCHAR2(200),
  IS_IDEMPOTENT    VARCHAR2(1),
  ADD_LOG          VARCHAR2(1),
  STATE            VARCHAR2(1),
  ACTION           VARCHAR2(1)   NOT NULL,
  ACTION_DATE      DATE          NOT NULL,
  CONSTRAINT ESBIN_R_METHODS_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_METHODS_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_R_METHODS_H_IX1 ON ESBIN_R_METHODS_H (METHOD_CODE) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_R_METHODS_H IS 'ESBIN_R_METHODS jadvali uchun o''zgartirishlar tarixi (audit log)';
COMMENT ON COLUMN ESBIN_R_METHODS_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN ESBIN_R_METHODS_H.ACTION IS 'Amal turi: I-insert, U-update, D-delete';
COMMENT ON COLUMN ESBIN_R_METHODS_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
