CREATE TABLE ESBIN_R_USER_METHOD_REL_H
(
  LOG_ID      NUMBER        NOT NULL,
  USER_ID     NUMBER        NOT NULL,
  METHOD_CODE VARCHAR2(100) NOT NULL,
  STATE       VARCHAR2(1),
  ACTION      VARCHAR2(1)   NOT NULL,
  ACTION_DATE DATE          NOT NULL,
  CONSTRAINT ESBIN_R_USER_METHOD_REL_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_USER_METHOD_REL_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_R_USER_METHOD_REL_H_IX1 ON ESBIN_R_USER_METHOD_REL_H (USER_ID, METHOD_CODE) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_R_USER_METHOD_REL_H IS 'ESBIN_R_USER_METHOD_REL jadvali uchun o''zgartirishlar tarixi (audit log) - kimga qaysi method qachon biriktirilgan/bekor qilingan';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL_H.ACTION IS 'Amal turi: I-insert (biriktirildi), D-delete (bekor qilindi)';
COMMENT ON COLUMN ESBIN_R_USER_METHOD_REL_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
