CREATE TABLE ESBIN_REQUESTS
(
  ID             NUMBER        NOT NULL,
  EXT_REQUEST_ID VARCHAR2(100) NOT NULL,
  PARTNER_CODE   VARCHAR2(50)  NOT NULL,
  USER_ID        NUMBER        NOT NULL,
  METHOD_CODE    VARCHAR2(100) NOT NULL,
  SM_PROCESS_ID  NUMBER,
  STATE          VARCHAR2(20)  DEFAULT 'RECEIVED' NOT NULL,
  SYNC_TYPE      VARCHAR2(1)   NOT NULL,
  CREATED_ON     DATE          DEFAULT SYSDATE NOT NULL,
  STARTED_ON     DATE,
  FINISHED_ON    DATE,
  DURATION_MS    NUMBER,
  IP_ADDRESS     VARCHAR2(45),
  CONSTRAINT ESBIN_REQUESTS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_REQUESTS_FK1 FOREIGN KEY (PARTNER_CODE) REFERENCES ESBIN_R_PARTNERS (PARTNER_CODE),
  CONSTRAINT ESBIN_REQUESTS_FK2 FOREIGN KEY (USER_ID) REFERENCES CORE_USERS (USER_ID),
  CONSTRAINT ESBIN_REQUESTS_FK3 FOREIGN KEY (METHOD_CODE) REFERENCES ESBIN_R_METHODS (METHOD_CODE),
  CONSTRAINT ESBIN_REQUESTS_C1 CHECK (STATE IN ('RECEIVED', 'QUEUED', 'RUNNING', 'SUCCESS', 'ERROR')),
  CONSTRAINT ESBIN_REQUESTS_C2 CHECK (SYNC_TYPE IN ('S', 'A'))
) TABLESPACE CORE_DATA;

CREATE UNIQUE INDEX ESBIN_REQUESTS_U1 ON ESBIN_REQUESTS (PARTNER_CODE, EXT_REQUEST_ID) TABLESPACE CORE_INDEX;
CREATE INDEX ESBIN_REQUESTS_IX1 ON ESBIN_REQUESTS (METHOD_CODE, CREATED_ON) TABLESPACE CORE_INDEX;
CREATE INDEX ESBIN_REQUESTS_IX2 ON ESBIN_REQUESTS (STATE) TABLESPACE CORE_INDEX;
CREATE INDEX ESBIN_REQUESTS_IX3 ON ESBIN_REQUESTS (USER_ID) TABLESPACE CORE_INDEX;
CREATE INDEX ESBIN_REQUESTS_IX4 ON ESBIN_REQUESTS (CREATED_ON) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_REQUESTS IS 'Har bir ESBIN so''rovi bo''yicha yengil/indekslangan (qidiruv uchun) yozuv';
COMMENT ON COLUMN ESBIN_REQUESTS.ID IS 'ESBIN''ning ichki so''rov identifikatori (partnerga qaytariladi)';
COMMENT ON COLUMN ESBIN_REQUESTS.EXT_REQUEST_ID IS 'Partner bergan tashqi so''rov identifikatori (idempotentlik/qidiruv uchun)';
COMMENT ON COLUMN ESBIN_REQUESTS.SM_PROCESS_ID IS 'SM_PROCESSES.ID - qaysi SM process bu so''rovni bajardi (ma''lumot uchun, ESBIN audit manbai emas)';
COMMENT ON COLUMN ESBIN_REQUESTS.STATE IS 'RECEIVED - qabul qilindi, QUEUED - async navbatda, RUNNING - bajarilmoqda, SUCCESS/ERROR - yakunlandi';
COMMENT ON COLUMN ESBIN_REQUESTS.SYNC_TYPE IS 'So''rov paytidagi ESBIN_R_METHODS.SYNCHRONIZE_TYPE nusxasi (metod keyin o''zgarsa ham tarixiy to''g''ri qolishi uchun)';
COMMENT ON COLUMN ESBIN_REQUESTS.DURATION_MS IS 'Bajarilish davomiyligi (millisekund), FINISHED_ON-STARTED_ON';
COMMENT ON COLUMN ESBIN_REQUESTS.IP_ADDRESS IS 'So''rov qaysi IP manzildan kelgani (Java qatlami beradi, ixtiyoriy) - IPv4/IPv6';
