CREATE TABLE ESBIN_R_PARTNERS
(
  PARTNER_CODE VARCHAR2(50)  NOT NULL,
  NAME         VARCHAR2(200) NOT NULL,
  STATE        VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  CONSTRAINT ESBIN_R_PARTNERS_PK PRIMARY KEY (PARTNER_CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_PARTNERS_C1 CHECK (STATE IN ('A', 'P'))
) TABLESPACE CORE_DATA;

COMMENT ON TABLE ESBIN_R_PARTNERS IS 'ESBIN (inbound ESB) orqali murojaat qiladigan tashqi hamkor tizimlar';
COMMENT ON COLUMN ESBIN_R_PARTNERS.PARTNER_CODE IS 'Hamkorning barqaror kodi';
COMMENT ON COLUMN ESBIN_R_PARTNERS.NAME IS 'Hamkor nomi';
COMMENT ON COLUMN ESBIN_R_PARTNERS.STATE IS 'A - active, P - passive';
