CREATE TABLE ESBIN_R_PARTNERS_H
(
  LOG_ID       NUMBER       NOT NULL,
  PARTNER_CODE VARCHAR2(50) NOT NULL,
  NAME         VARCHAR2(200),
  STATE        VARCHAR2(1),
  ACTION       VARCHAR2(1)  NOT NULL,
  ACTION_DATE  DATE         NOT NULL,
  CONSTRAINT ESBIN_R_PARTNERS_H_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_PARTNERS_H_C1 CHECK (ACTION IN ('I', 'U', 'D'))
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_R_PARTNERS_H_IX1 ON ESBIN_R_PARTNERS_H (PARTNER_CODE) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_R_PARTNERS_H IS 'ESBIN_R_PARTNERS jadvali uchun o''zgartirishlar tarixi (audit log)';
COMMENT ON COLUMN ESBIN_R_PARTNERS_H.LOG_ID IS 'Tarix yozuvining unikal identifikatori';
COMMENT ON COLUMN ESBIN_R_PARTNERS_H.ACTION IS 'Amal turi: I-insert, U-update, D-delete';
COMMENT ON COLUMN ESBIN_R_PARTNERS_H.ACTION_DATE IS 'Amal bajarilgan vaqt';
