CREATE TABLE ESBIN_R_METHODS
(
  METHOD_CODE      VARCHAR2(100) NOT NULL,
  NAME             VARCHAR2(500) NOT NULL,
  PROCESS_CODE     VARCHAR2(100) NOT NULL,
  REQUEST_TYPE     VARCHAR2(10)  DEFAULT 'POST' NOT NULL,
  SYNCHRONIZE_TYPE VARCHAR2(1)   DEFAULT 'S' NOT NULL,
  RESULT_FUNCTION  VARCHAR2(200),
  IS_IDEMPOTENT    VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  ADD_LOG          VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  STATE            VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  CONSTRAINT ESBIN_R_METHODS_PK PRIMARY KEY (METHOD_CODE) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_METHODS_C1 CHECK (REQUEST_TYPE IN ('GET', 'POST')),
  CONSTRAINT ESBIN_R_METHODS_C2 CHECK (SYNCHRONIZE_TYPE IN ('S', 'A')),
  CONSTRAINT ESBIN_R_METHODS_C3 CHECK (IS_IDEMPOTENT IN ('Y', 'N')),
  CONSTRAINT ESBIN_R_METHODS_C4 CHECK (ADD_LOG IN ('Y', 'N')),
  CONSTRAINT ESBIN_R_METHODS_C5 CHECK (STATE IN ('A', 'P')),
  CONSTRAINT ESBIN_R_METHODS_C6 CHECK (RESULT_FUNCTION IS NULL OR SYNCHRONIZE_TYPE = 'A')
) TABLESPACE CORE_DATA;

COMMENT ON TABLE ESBIN_R_METHODS IS 'Tashqi hamkorlarga ochilgan ESBIN metodlari - har biri mavjud SM process_code''ga bog''lanadi';
COMMENT ON COLUMN ESBIN_R_METHODS.METHOD_CODE IS 'Tashqi hamkor chaqiradigan barqaror method kodi';
COMMENT ON COLUMN ESBIN_R_METHODS.NAME IS 'Method tavsifi';
COMMENT ON COLUMN ESBIN_R_METHODS.PROCESS_CODE IS 'Birlamchi ishga tushirish har doim shu SM process_code orqali (Core_Api.Execute_Process_Clob) - istisnosiz majburiy';
COMMENT ON COLUMN ESBIN_R_METHODS.REQUEST_TYPE IS 'GET yoki POST';
COMMENT ON COLUMN ESBIN_R_METHODS.SYNCHRONIZE_TYPE IS 'S - sinxron (javob darhol HTTP javobida), A - asinxron (navbatga qo''yiladi, natija keyin GET_REQUEST_RESULT bilan so''raladi)';
COMMENT ON COLUMN ESBIN_R_METHODS.RESULT_FUNCTION IS 'Faqat SYNCHRONIZE_TYPE=A uchun, ixtiyoriy: natija ESBIN o''z logidan emas, shu function orqali tegishli moduldan jonli olinadi';
COMMENT ON COLUMN ESBIN_R_METHODS.IS_IDEMPOTENT IS 'Y bo''lsa (partner_code, ext_request_id) takrorlanishi taqiqlanadi';
COMMENT ON COLUMN ESBIN_R_METHODS.ADD_LOG IS 'ESBIN o''zining request/response logini shu method uchun yozsinmi (standart - Y)';
COMMENT ON COLUMN ESBIN_R_METHODS.STATE IS 'A - active, P - passive';
