CREATE TABLE ESBIN_R_PARTNER_USERS
(
  PARTNER_CODE VARCHAR2(50) NOT NULL,
  USER_ID      NUMBER       NOT NULL,
  STATE        VARCHAR2(1)  DEFAULT 'A' NOT NULL,
  CONSTRAINT ESBIN_R_PARTNER_USERS_PK PRIMARY KEY (PARTNER_CODE, USER_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_R_PARTNER_USERS_FK1 FOREIGN KEY (PARTNER_CODE) REFERENCES ESBIN_R_PARTNERS (PARTNER_CODE),
  CONSTRAINT ESBIN_R_PARTNER_USERS_FK2 FOREIGN KEY (USER_ID) REFERENCES CORE_USERS (USER_ID),
  CONSTRAINT ESBIN_R_PARTNER_USERS_C1 CHECK (STATE IN ('A', 'P'))
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_R_PARTNER_USERS_IX1 ON ESBIN_R_PARTNER_USERS (USER_ID) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_R_PARTNER_USERS IS 'Hamkorning texnik (virtual) userlari - haqiqiy CORE_USERS qatorlari, ruxsatlari mavjud access tizimi orqali boshqariladi';
COMMENT ON COLUMN ESBIN_R_PARTNER_USERS.PARTNER_CODE IS 'ESBIN_R_PARTNERS.PARTNER_CODE';
COMMENT ON COLUMN ESBIN_R_PARTNER_USERS.USER_ID IS 'CORE_USERS.USER_ID - haqiqiy (texnik) user';
COMMENT ON COLUMN ESBIN_R_PARTNER_USERS.STATE IS 'A - active, P - passive';
