CREATE TABLE ESBIN_PARTNER_TOKENS
(
  USER_ID       NUMBER        NOT NULL,
  LOGIN         VARCHAR2(100) NOT NULL,
  ACCESS_TOKEN  VARCHAR2(500) NOT NULL,
  REFRESH_TOKEN VARCHAR2(500),
  CREATED_ON    DATE          DEFAULT SYSDATE NOT NULL,
  MODIFY_ON     DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT ESBIN_PARTNER_TOKENS_PK PRIMARY KEY (USER_ID) USING INDEX TABLESPACE CORE_INDEX,
  CONSTRAINT ESBIN_PARTNER_TOKENS_FK1 FOREIGN KEY (USER_ID) REFERENCES CORE_USERS (USER_ID)
) TABLESPACE CORE_DATA;

CREATE INDEX ESBIN_PARTNER_TOKENS_IX1 ON ESBIN_PARTNER_TOKENS (ACCESS_TOKEN) TABLESPACE CORE_INDEX;

COMMENT ON TABLE ESBIN_PARTNER_TOKENS IS 'Texnik userlarning joriy access/refresh tokenlari (operatsion cache, tarixi saqlanmaydi)';
COMMENT ON COLUMN ESBIN_PARTNER_TOKENS.USER_ID IS 'CORE_USERS.USER_ID';
COMMENT ON COLUMN ESBIN_PARTNER_TOKENS.LOGIN IS 'Login (autentifikatsiya uchun)';
