
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_PRINT_HISTORY_T1"
    BEFORE INSERT ON MPT_PRINT_HISTORY
    FOR EACH ROW
     WHEN (NEW.HISTORY_ID IS NULL) BEGIN
    :NEW.HISTORY_ID := MPT_PRINT_HISTORY_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_PRINT_HISTORY_T1" ENABLE;

