
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_PRINT_SETTINGS_T1"
    BEFORE INSERT ON MPT_PRINT_SETTINGS
    FOR EACH ROW
     WHEN (NEW.SETTING_ID IS NULL) BEGIN
    :NEW.SETTING_ID := MPT_PRINT_SETTINGS_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_PRINT_SETTINGS_T1" ENABLE;

