
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_PRINT_QR_CODES_T1"
    BEFORE INSERT ON MPT_PRINT_QR_CODES
    FOR EACH ROW
     WHEN (NEW.QR_ID IS NULL) BEGIN
    :NEW.QR_ID := MPT_PRINT_QR_CODES_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_PRINT_QR_CODES_T1" ENABLE;

