
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_PRINT_VARIABLES_T1"
    BEFORE INSERT OR UPDATE OF VARIABLE_CODE, SCOPE ON MPT_PRINT_VARIABLES
    FOR EACH ROW
BEGIN
    MPT_PRINT_API.validate_variable_code(:NEW.VARIABLE_CODE, :NEW.SCOPE);
END;


/
ALTER TRIGGER "MPT_PRINT_VARIABLES_T1" ENABLE;

