
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_TEMPLATE_VAR_MAPPING_DOC_T1"
    BEFORE INSERT ON MPT_TEMPLATE_VAR_MAPPING_DOC
    FOR EACH ROW
     WHEN (NEW.MAPPING_ID IS NULL) BEGIN
    :NEW.MAPPING_ID := MPT_TEMPLATE_VAR_MAPPING_DOC_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_TEMPLATE_VAR_MAPPING_DOC_T1" ENABLE;

