
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_TEMPLATE_TYPE_VARS_T1"
    BEFORE INSERT OR UPDATE ON MPT_TEMPLATE_TYPE_VARS
    FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.MAPPING_ID IS NULL THEN
        :NEW.MAPPING_ID := MPT_TEMPLATE_TYPE_VARS_S1.NEXTVAL;
    END IF;
    -- PLACEHOLDER doim variable_code'dan olinadi: [variable_code].
    -- Admin uni qo'lda kiritmaydi, forma yubormaydi.
    :NEW.PLACEHOLDER := '[' || :NEW.VARIABLE_CODE || ']';
END;
/
ALTER TRIGGER "MPT_TEMPLATE_TYPE_VARS_T1" ENABLE;
