
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_PRINT_SETTING_FILES_T1"
    BEFORE INSERT ON MPT_PRINT_SETTING_FILES
    FOR EACH ROW
     WHEN (NEW.SETTING_FILE_ID IS NULL) BEGIN
    :NEW.SETTING_FILE_ID := MPT_PRINT_SETTING_FILES_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_PRINT_SETTING_FILES_T1" ENABLE;

