
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_TEMPLATE_CELL_MAPPING_T1"
    BEFORE INSERT ON MPT_TEMPLATE_CELL_MAPPING
    FOR EACH ROW
     WHEN (NEW.MAPPING_ID IS NULL) BEGIN
    :NEW.MAPPING_ID := MPT_TEMPLATE_CELL_MAPPING_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_TEMPLATE_CELL_MAPPING_T1" ENABLE;

