
  CREATE OR REPLACE EDITIONABLE TRIGGER "MPT_TRANSLIT_RULE_T1"
    BEFORE INSERT ON MPT_TRANSLIT_RULE
    FOR EACH ROW
     WHEN (NEW.RULE_ID IS NULL) BEGIN
    :NEW.RULE_ID := MPT_TRANSLIT_RULE_S1.NEXTVAL;
END;
/
ALTER TRIGGER "MPT_TRANSLIT_RULE_T1" ENABLE;

