--------------------------------------------------------------------------------
-- CoreBank | Fabrika produktov — "Тип счёта" (Hisob turi) справочnigi
-- Manba: fabrika-produktov.html — "Тип счёта" ro'yxat oynasi, uning
--        "Изменение/Новый тип счёта" formasi, ochiladigan "дочерняя запись"
--        (Тип клиента / Коды COA / Валюта) formasi va "История изменений" oynasi.
--
-- Uslub avvalgi "Fizik shaxs mijoz kartochkasi" skripti bilan bir xil:
--   1) Jadval nomlari inglizcha ko'plikda
--   2) Har bir ma'lumot alohida atomik ustunda (birlashtirilgan ustun yo'q)
--   3) Nomenklatura xarakteridagi ma'lumotlar (Modul, Hisob sinflari spravochnigi)
--      alohida ACC_R_ prefiksli jadvallarga chiqarilgan
--   4) Barcha cheklovlar (PK/FK/UNIQUE/CHECK) CREATE TABLE ichida emas, balki
--      alohida ALTER TABLE ... ADD CONSTRAINT operatorlari orqali qo'shiladi,
--      nomlash: <JADVAL>_PK, <JADVAL>_F1.._Fn, <JADVAL>_U1.._Un, <JADVAL>_C1.._Cn
--   5) Har bir jadvalning cheklovlari va indekslari o'sha jadvalning CREATE TABLE
--      bayonotidan darhol keyin joylashtirilgan (indekslar: <JADVAL>_I1, _I2 ...)
--
-- Prefikslar:
--   ACC_R_  — spravochnik (ma'lumotnoma) jadvallari: Modul, Hisob sinflari katalogi
--   ACC_    — "Тип счёта" ierarxik spravochnigiga tegishli asosiy jadvallar
--             (ota yozuv, dochernie zapisi, o'zgarishlar tarixi)
--------------------------------------------------------------------------------


--================================================================================
-- QISM A. SPRAVOCHNIK (MA'LUMOTNOMA) JADVALLARI — prefiks ACC_R_
-- Har bir jadval blokida: CREATE TABLE -> COMMENT -> cheklovlar (ALTER TABLE) -> indekslar
--================================================================================

--------------------------------------------------------------------------------
-- A1) ACC_R_MODULES — Bank moduli spravochnigi (Kredit, Depozit, Karta va h.k.)
--------------------------------------------------------------------------------
CREATE TABLE ACC_R_MODULES (
  MODULE_CODE  VARCHAR2(10)   NOT NULL,
  MODULE_NAME  VARCHAR2(100)  NOT NULL
);

COMMENT ON TABLE ACC_R_MODULES IS 'Bank modullari spravochnigi. "Тип счёта" formasidagi "Модуль" tanlov ro''yxatiga (LN, DEP, SV, CARD, GUAR, MT, UTIL, FX) mos keladi.';
COMMENT ON COLUMN ACC_R_MODULES.MODULE_CODE IS 'Modul kodi (PK), masalan "DEP"';
COMMENT ON COLUMN ACC_R_MODULES.MODULE_NAME IS 'Modul nomi, masalan "Депозит"';

-- ACC_R_MODULES: cheklovlar (constraints)
ALTER TABLE ACC_R_MODULES ADD CONSTRAINT ACC_R_MODULES_PK PRIMARY KEY (MODULE_CODE);


--------------------------------------------------------------------------------
-- A2) ACC_R_CLASS_CATALOG — "Типы счетов — справочник" oynasi
--    (bank sohasida qabul qilingan balansli hisoblar sinflarining namunaviy
--    tarkibi; ma'lumotnoma xarakterida, "Тип счёта" yozuvlariga FK bilan
--    bog'lanmagan — faqat mo'ljal/namuna sifatida ko'rsatiladi)
--------------------------------------------------------------------------------
CREATE TABLE ACC_R_CLASS_CATALOG (
  CATALOG_ID    NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
  CLASS_CODE    VARCHAR2(2)    NOT NULL,
  RANGE_FROM    VARCHAR2(10)   NOT NULL,
  RANGE_TO      VARCHAR2(10)   NOT NULL,
  CATALOG_NAME  VARCHAR2(200)  NOT NULL,
  CATALOG_DESC  VARCHAR2(500)
);

COMMENT ON TABLE ACC_R_CLASS_CATALOG IS
  '"Типы счетов — справочник" oynasidagi namunaviy hisob sinflari ro''yxati
   (masalan Sinf 2: "Depozit hisoblari", diapazon 20400-20499). Illyustrativ
   ma''lumotnoma, "Тип счёта" ierarxiyasiga bevosita bog''lanmagan.';

COMMENT ON COLUMN ACC_R_CLASS_CATALOG.CATALOG_ID   IS 'Katalog yozuvining unikal identifikatori (PK) — bitta sinf (CLASS_CODE) bo''yicha bir nechta diapazon bo''lishi mumkinligi uchun alohida surrogat kalit';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG.CLASS_CODE   IS 'Hisob sinfi raqami ("Класс" ustuni), masalan "2"';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG.RANGE_FROM   IS 'Hisoblar diapazonining boshlanishi ("Диапазон счетов" ustunidan ajratilgan, masalan "20101")';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG.RANGE_TO     IS 'Hisoblar diapazonining tugashi ("Диапазон счетов" ustunidan ajratilgan, masalan "20999")';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG.CATALOG_NAME IS 'Sinf nomi ("Наименование" ustuni), masalan "Наличность и драгоценные металлы"';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG.CATALOG_DESC IS 'Sinf tavsifi ("Описание" ustuni)';

-- ACC_R_CLASS_CATALOG: cheklovlar (constraints)
ALTER TABLE ACC_R_CLASS_CATALOG ADD CONSTRAINT ACC_R_CLASS_CATALOG_PK PRIMARY KEY (CATALOG_ID);


--------------------------------------------------------------------------------
-- A3) ACC_R_CLASS_CATALOG_MODULES — Sinf <-> Modul bog'lanish jadvali (N:N)
--    ("Обычно используется в модулях" ustuni bir nechta modulni bir vergul
--    bilan sanab o'tgani uchun ko'p-ko'pga bog'lanish sifatida ajratilgan)
--------------------------------------------------------------------------------
CREATE TABLE ACC_R_CLASS_CATALOG_MODULES (
  CATALOG_ID   NUMBER(19)    NOT NULL,
  MODULE_CODE  VARCHAR2(10)  NOT NULL
);

COMMENT ON TABLE ACC_R_CLASS_CATALOG_MODULES IS
  'ACC_R_CLASS_CATALOG va ACC_R_MODULES orasidagi ko''p-ko''pga (N:N) bog''lanish
   jadvali — "Обычно используется в модулях" ustunidagi ro''yxat (masalan
   "CARD, DEP") shu jadvalda alohida-alohida qatorlarda saqlanadi.';

COMMENT ON COLUMN ACC_R_CLASS_CATALOG_MODULES.CATALOG_ID  IS 'Hisob sinfi katalog yozuvi, FK -> ACC_R_CLASS_CATALOG.CATALOG_ID';
COMMENT ON COLUMN ACC_R_CLASS_CATALOG_MODULES.MODULE_CODE IS 'Modul kodi, FK -> ACC_R_MODULES.MODULE_CODE';

-- ACC_R_CLASS_CATALOG_MODULES: cheklovlar (constraints)
ALTER TABLE ACC_R_CLASS_CATALOG_MODULES ADD CONSTRAINT ACC_R_CLASS_CATALOG_MODULES_PK PRIMARY KEY (CATALOG_ID, MODULE_CODE);
ALTER TABLE ACC_R_CLASS_CATALOG_MODULES ADD CONSTRAINT ACC_R_CLASS_CATALOG_MODULES_F1 FOREIGN KEY (CATALOG_ID) REFERENCES ACC_R_CLASS_CATALOG (CATALOG_ID) ON DELETE CASCADE;
ALTER TABLE ACC_R_CLASS_CATALOG_MODULES ADD CONSTRAINT ACC_R_CLASS_CATALOG_MODULES_F2 FOREIGN KEY (MODULE_CODE)  REFERENCES ACC_R_MODULES (MODULE_CODE);

-- ACC_R_CLASS_CATALOG_MODULES: indekslar
CREATE INDEX ACC_R_CLASS_CATALOG_MODULES_I1 ON ACC_R_CLASS_CATALOG_MODULES (MODULE_CODE);


--================================================================================
-- QISM B. "ТИП СЧЁТА" IERARXIK SPRAVOCHNIGIGA TEGISHLI JADVALLAR — prefiks ACC_
-- Har bir jadval blokida: CREATE TABLE -> COMMENT -> cheklovlar (ALTER TABLE) -> indekslar
--================================================================================

--------------------------------------------------------------------------------
-- B1) ACC_ACCOUNT_TYPES — "Тип счёта" ro'yxati (ota yozuv)
--------------------------------------------------------------------------------
CREATE TABLE ACC_ACCOUNT_TYPES (
  ACCOUNT_TYPE_ID       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  NAME                  VARCHAR2(200) NOT NULL,
  MODULE_CODE           VARCHAR2(10)  NOT NULL,
  BALANCE_TYPE          VARCHAR2(20)  NOT NULL,
  STATE                 VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  UNIQUE_CONTRACT_FLAG  CHAR(1)       DEFAULT 'N' NOT NULL,
  IS_OPEN_FLAG          CHAR(1)       DEFAULT 'Y' NOT NULL,
  INCODE_TYPE           VARCHAR2(1)   NOT NULL,
  IS_VIRTUAL            VARCHAR2(1)   NOT NULL,
  OBJECT_CODE           VARCHAR2(100),
  CREATED_ON            DATE          DEFAULT SYSDATE NOT NULL,
  CREATED_BY            VARCHAR2(50)  DEFAULT USER NOT NULL,
  MODIFIED_ON           DATE,
  MODIFIED_BY           VARCHAR2(50)
);

COMMENT ON TABLE ACC_ACCOUNT_TYPES IS
  '"Тип счёта" ro''yxat oynasidagi ota (parent) yozuvlar — balansli/vnebalans
   hisoblarning modul va holat bo''yicha meppingi. Ko''rinadigan hisob kodi
   ("Тип счёт ID" ustuni, masalan "СЧ-00005") saqlanmaydi — u ACCOUNT_TYPE_ID
   asosida "СЧ-" + LPAD(ACCOUNT_TYPE_ID,5,''0'') formulasi bilan hosil qilinadi.';

COMMENT ON COLUMN ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID      IS 'Hisob turi yozuvining unikal identifikatori (PK), ko''rinadigan "СЧ-00005" kodi shu qiymatdan hosil qilinadi';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.NAME                 IS 'Hisob turining nomi/nomlanishi (masalan "Jismoniy shaxs depozit hisobi")';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.MODULE_CODE          IS 'Modul, FK -> ACC_R_MODULES.MODULE_CODE ("Модуль" ustuni)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.BALANCE_TYPE         IS 'Баланс / внебаланс: "Баланс" yoki "Внебаланс"';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.STATE                IS 'Holati: A — Актив, P — Пассив';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.UNIQUE_CONTRACT_FLAG IS 'Uникал. договор belgisi: Y — har shartnoma uchun alohida (unikal) hisob, N — yo''q';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.IS_OPEN_FLAG         IS 'IsOpen belgisi: Y — hisob ochiq/mavjud (True), N — yopiq (False)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.INCODE_TYPE          IS 'Hisob raqami kodlash turi: C — Credit, D — Debit';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.IS_VIRTUAL           IS 'Virtual hisob belgisi: Y — virtual hisob, N — oddiy (jismoniy) hisob';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.OBJECT_CODE          IS 'Bog''liq obyekt kodi (masalan tashqi tizim yoki hisob shablonidagi obyekt identifikatori)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.CREATED_ON           IS 'Yozuv yaratilgan sana/vaqt';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.CREATED_BY           IS 'Yozuvni yaratgan foydalanuvchi (operator) login';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.MODIFIED_ON          IS 'Yozuv oxirgi marta o''zgartirilgan sana/vaqt';
COMMENT ON COLUMN ACC_ACCOUNT_TYPES.MODIFIED_BY          IS 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi (operator) login';

-- ACC_ACCOUNT_TYPES: cheklovlar (constraints)
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_PK PRIMARY KEY (ACCOUNT_TYPE_ID);
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_F1 FOREIGN KEY (MODULE_CODE) REFERENCES ACC_R_MODULES (MODULE_CODE);
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C1 CHECK (BALANCE_TYPE IN ('Баланс','Внебаланс'));
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C2 CHECK (STATE IN ('A','P'));
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C3 CHECK (UNIQUE_CONTRACT_FLAG IN ('Y','N'));
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C4 CHECK (IS_OPEN_FLAG IN ('Y','N'));
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C5 CHECK (INCODE_TYPE IN ('C','D'));
ALTER TABLE ACC_ACCOUNT_TYPES ADD CONSTRAINT ACC_ACCOUNT_TYPES_C6 CHECK (IS_VIRTUAL IN ('Y','N'));

-- ACC_ACCOUNT_TYPES: indekslar
CREATE INDEX ACC_ACCOUNT_TYPES_I1 ON ACC_ACCOUNT_TYPES (MODULE_CODE);


--------------------------------------------------------------------------------
-- B2) ACC_ACCOUNT_TYPE_CLIENTS — "дочерняя запись" (Тип клиента / COA код / Валюта)
--    Eslatma: MODULE_CODE, BALANCE_TYPE, UNIQUE_CONTRACT_FLAG, IS_OPEN_FLAG kabi
--    ota yozuvdan olinadigan ma'lumotlar bu yerda takrorlanmaydi — ular
--    ACC_ACCOUNT_TYPES jadvalidan JOIN orqali olinadi (formaning o'zi ham bu
--    ma'lumotlarni faqat ko'rsatish uchun "nusxa" qiladi, DBda saqlash shart
--    emas).
--------------------------------------------------------------------------------
CREATE TABLE ACC_ACCOUNT_TYPE_CLIENTS (
  ACCOUNT_TYPE_CLIENT_ID  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  ACCOUNT_TYPE_ID         NUMBER(19)    NOT NULL,
  CLIENT_TYPE             VARCHAR2(1)   NOT NULL,
  STATE                   VARCHAR2(1)   DEFAULT 'A' NOT NULL,
  CODE_COA                VARCHAR2(20)  NOT NULL,
  CURRENCY_CODE           VARCHAR2(5),
  CREATED_ON              DATE          DEFAULT SYSDATE NOT NULL,
  CREATED_BY              VARCHAR2(50)  DEFAULT USER NOT NULL,
  MODIFIED_ON             DATE,
  MODIFIED_BY             VARCHAR2(50)
);

COMMENT ON TABLE ACC_ACCOUNT_TYPE_CLIENTS IS
  '"Тип счёта" satrini ochganda ko''rinadigan dochernie zapisi (Тип клиента /
   Коды COA / Валюта). Bitta "Тип счёта" yozuviga bir nechta dochernie zapisi
   biriktirilishi mumkin (1:N) — jadvalda "Дочерних записей" ustunida sanaladi.';

COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.ACCOUNT_TYPE_CLIENT_ID IS 'Dochernie zapisi unikal identifikatori (PK)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.ACCOUNT_TYPE_ID        IS 'Ota "Тип счёта" yozuviga FK -> ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.CLIENT_TYPE            IS 'Тип клиента: C — Клиент, B — bank';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.STATE                  IS 'Holati: A — Актив, P — Пассив';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.CODE_COA               IS 'Коды COA (Баланс код) — majburiy, masalan "20406"';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.CURRENCY_CODE          IS 'Валюта kodi (masalan UZS/USD/EUR); "*" qiymati barcha valyutalar uchun mosligini bildiradi ("* — подходит для всех")';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.CREATED_ON             IS 'Yozuv yaratilgan sana/vaqt';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.CREATED_BY             IS 'Yozuvni yaratgan foydalanuvchi (operator) login';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.MODIFIED_ON            IS 'Yozuv oxirgi marta o''zgartirilgan sana/vaqt';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_CLIENTS.MODIFIED_BY            IS 'Yozuvni oxirgi marta o''zgartirgan foydalanuvchi (operator) login';

-- ACC_ACCOUNT_TYPE_CLIENTS: cheklovlar (constraints)
ALTER TABLE ACC_ACCOUNT_TYPE_CLIENTS ADD CONSTRAINT ACC_ACCOUNT_TYPE_CLIENTS_PK PRIMARY KEY (ACCOUNT_TYPE_CLIENT_ID);
ALTER TABLE ACC_ACCOUNT_TYPE_CLIENTS ADD CONSTRAINT ACC_ACCOUNT_TYPE_CLIENTS_F1 FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACC_ACCOUNT_TYPES (ACCOUNT_TYPE_ID) ON DELETE CASCADE;
ALTER TABLE ACC_ACCOUNT_TYPE_CLIENTS ADD CONSTRAINT ACC_ACCOUNT_TYPE_CLIENTS_U1 UNIQUE (ACCOUNT_TYPE_ID, CODE_COA);
ALTER TABLE ACC_ACCOUNT_TYPE_CLIENTS ADD CONSTRAINT ACC_ACCOUNT_TYPE_CLIENTS_C1 CHECK (CLIENT_TYPE IN ('C','B'));
ALTER TABLE ACC_ACCOUNT_TYPE_CLIENTS ADD CONSTRAINT ACC_ACCOUNT_TYPE_CLIENTS_C2 CHECK (STATE IN ('A','P'));

-- ACC_ACCOUNT_TYPE_CLIENTS: indekslar
-- (ACCOUNT_TYPE_ID uchun alohida indeks shart emas — ACC_ACCOUNT_TYPE_CLIENTS_U1
--  tarkibida allaqachon yetakchi ustun sifatida indekslangan.)


--------------------------------------------------------------------------------
-- B3) ACC_ACCOUNT_TYPE_HISTORY — "История изменений" oynasi
--------------------------------------------------------------------------------
CREATE TABLE ACC_ACCOUNT_TYPE_HISTORY (
  HISTORY_ID       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  ACCOUNT_TYPE_ID  NUMBER(19)    NOT NULL,
  ACTION_CODE      VARCHAR2(20)  NOT NULL,
  MODIFIED_ON      DATE          DEFAULT SYSDATE NOT NULL,
  MODIFIED_BY      VARCHAR2(50)  DEFAULT USER NOT NULL,
  BEFORE_SNAPSHOT  CLOB,
  AFTER_SNAPSHOT   CLOB          NOT NULL
);

COMMENT ON TABLE ACC_ACCOUNT_TYPE_HISTORY IS
  '"История изменений записи" oynasidagi o''zgarishlar jurnali — har bir
   "Тип счёта" yozuvi bo''yicha yaratilish/o''zgartirish harakati va uning
   oldingi/keyingi holatining JSON ko''rinishidagi tasviri.';

COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.HISTORY_ID      IS 'Tarix yozuvining unikal identifikatori (PK)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.ACCOUNT_TYPE_ID IS '"Тип счёта" yozuviga FK -> ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.ACTION_CODE     IS 'Harakat turi: CREATE — Создание, UPDATE — Изменение, DELETE — Удаление';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.MODIFIED_ON     IS 'O''zgarish sodir bo''lgan sana/vaqt';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.MODIFIED_BY     IS 'O''zgarishni amalga oshirgan foydalanuvchi (operator) login';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.BEFORE_SNAPSHOT IS 'O''zgarishdan oldingi holat, JSON ko''rinishida (CREATE harakati uchun NULL)';
COMMENT ON COLUMN ACC_ACCOUNT_TYPE_HISTORY.AFTER_SNAPSHOT  IS 'O''zgarishdan keyingi holat, JSON ko''rinishida (har doim to''ldiriladi)';

-- ACC_ACCOUNT_TYPE_HISTORY: cheklovlar (constraints)
ALTER TABLE ACC_ACCOUNT_TYPE_HISTORY ADD CONSTRAINT ACC_ACCOUNT_TYPE_HISTORY_PK PRIMARY KEY (HISTORY_ID);
ALTER TABLE ACC_ACCOUNT_TYPE_HISTORY ADD CONSTRAINT ACC_ACCOUNT_TYPE_HISTORY_F1 FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACC_ACCOUNT_TYPES (ACCOUNT_TYPE_ID) ON DELETE CASCADE;
ALTER TABLE ACC_ACCOUNT_TYPE_HISTORY ADD CONSTRAINT ACC_ACCOUNT_TYPE_HISTORY_C1 CHECK (ACTION_CODE IN ('CREATE','UPDATE','DELETE'));
ALTER TABLE ACC_ACCOUNT_TYPE_HISTORY ADD CONSTRAINT ACC_ACCOUNT_TYPE_HISTORY_C2 CHECK (BEFORE_SNAPSHOT IS JSON);
ALTER TABLE ACC_ACCOUNT_TYPE_HISTORY ADD CONSTRAINT ACC_ACCOUNT_TYPE_HISTORY_C3 CHECK (AFTER_SNAPSHOT IS JSON);

-- ACC_ACCOUNT_TYPE_HISTORY: indekslar
CREATE INDEX ACC_ACCOUNT_TYPE_HISTORY_I1 ON ACC_ACCOUNT_TYPE_HISTORY (ACCOUNT_TYPE_ID);


--------------------------------------------------------------------------------
-- Izoh: ACC_ACCOUNT_TYPES.ACCOUNT_TYPE_ID ga bog'liq ACC_ACCOUNT_TYPE_CLIENTS va
-- ACC_ACCOUNT_TYPE_HISTORY jadvallari ON DELETE CASCADE bilan bog'langan — ota
-- "Тип счёта" yozuvi o'chirilganda uning barcha dochernie zapisi va tarix
-- yozuvlari ham o'chadi. Spravochnik (ACC_R_*) jadvallari CASCADE bilan
-- bog'lanmagan va mustaqil boshqariladi.
--------------------------------------------------------------------------------
