SET LINESIZE 200
WHENEVER SQLERROR CONTINUE

-- MUHIM QOIDA: UAPP (webapp/JSP) hech qachon PF_* jadvalga to'g'ridan-to'g'ri
-- SELECT/DML huquqiga ega bo'lmasligi kerak - faqat tegishli _V view'lar
-- orqali. Yozish faqat SM process (Core_Api.Execute_Process_Clob) orqali.
-- Yangi o'qish ehtiyoji chiqsa: mos view yo'q bo'lsa yangisini yarat, keyin
-- shu view'ga grant ber - jadvalga emas.

GRANT SELECT ON PF_R_CATEGORIES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_CATEGORIES_V FOR CORE.PF_R_CATEGORIES_V;

GRANT SELECT ON PF_R_ATTRIBUTES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_ATTRIBUTES_V FOR CORE.PF_R_ATTRIBUTES_V;

GRANT SELECT ON PF_R_ATTRIBUTE_CATEGORIES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_ATTRIBUTE_CATEGORIES_V FOR CORE.PF_R_ATTRIBUTE_CATEGORIES_V;

GRANT SELECT ON PF_R_PARAMETERS_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_PARAMETERS_V FOR CORE.PF_R_PARAMETERS_V;

GRANT SELECT ON PF_R_PRODUCT_DELIVERY_TYPES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_PRODUCT_DELIVERY_TYPES_V FOR CORE.PF_R_PRODUCT_DELIVERY_TYPES_V;

GRANT SELECT ON PF_R_PRODUCT_STATES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_PRODUCT_STATES_V FOR CORE.PF_R_PRODUCT_STATES_V;

GRANT SELECT ON PF_R_REFERENCE_VIEWS_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_R_REFERENCE_VIEWS_V FOR CORE.PF_R_REFERENCE_VIEWS_V;

GRANT SELECT ON PF_PRODUCTS_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_PRODUCTS_V FOR CORE.PF_PRODUCTS_V;

GRANT SELECT ON PF_PRODUCT_PARAMETER_VALUES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_PRODUCT_PARAMETER_VALUES_V FOR CORE.PF_PRODUCT_PARAMETER_VALUES_V;

GRANT SELECT ON PF_VERSION_RULES_V TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_VERSION_RULES_V FOR CORE.PF_VERSION_RULES_V;

GRANT EXECUTE ON PF_SM_API TO UAPP;
CREATE OR REPLACE SYNONYM UAPP.PF_SM_API FOR CORE.PF_SM_API;

PROMPT === tekshirish: PF% jadvallariga (view emas) UAPP granti bolmasligi kerak ===
SELECT p.TABLE_NAME, o.OBJECT_TYPE
  FROM ALL_TAB_PRIVS p
  JOIN ALL_OBJECTS o ON o.OBJECT_NAME = p.TABLE_NAME AND o.OWNER = p.TABLE_SCHEMA
 WHERE p.GRANTEE = 'UAPP' AND p.TABLE_SCHEMA = 'CORE' AND p.TABLE_NAME LIKE 'PF%' AND o.OBJECT_TYPE = 'TABLE';
